# WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
# Edits need to be made to the proto files
# (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/offboard/offboard.proto)

"""
Control a drone with position, velocity, attitude or motor commands.

 The module is called offboard because the commands can be sent from external sources
 as opposed to onboard control right inside the autopilot "board".

 Client code must specify a setpoint before starting offboard mode.
 Mavsdk automatically sends setpoints at 20Hz (PX4 Offboard mode requires that setpoints
 are minimally sent at 2Hz).
"""

# Import main plugin class
from .offboard import Offboard

# Import enums

# Import result enum
from .offboard import OffboardResult

# Import data structures
from .offboard import Attitude
from .offboard import ActuatorControlGroup
from .offboard import ActuatorControl
from .offboard import AttitudeRate
from .offboard import PositionNedYaw
from .offboard import PositionGlobalYaw
from .offboard import VelocityBodyYawspeed
from .offboard import VelocityNedYaw
from .offboard import AccelerationNed

# Define __all__ for explicit exports
__all__ = [
    "Offboard",
    "OffboardResult",
    "Attitude",
    "ActuatorControlGroup",
    "ActuatorControl",
    "AttitudeRate",
    "PositionNedYaw",
    "PositionGlobalYaw",
    "AltitudeType",
    "VelocityBodyYawspeed",
    "VelocityNedYaw",
    "AccelerationNed",
]
