// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/failure/failure.proto)

package io.mavsdk.kotlin.plugins.failure

import io.mavsdk.jni.plugins.failure.NativeFailure

private class FailureNativeImpl(
    private val handle: Long
) : FailureNative {
    override fun inject(failureUnit: Failure.FailureUnit, failureType: Failure.FailureType, instance: Int): Int =
        NativeFailure.inject(handle, failureUnit.value, failureType.value, instance)

    override fun destroy() {
        NativeFailure.destroy(handle)
    }
}

internal actual fun createFailureNative(systemHandle: Long): FailureNative =
    FailureNativeImpl(NativeFailure.create(systemHandle))
