// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/geofence/geofence.proto)

#include <jni.h>
#include "cmavsdk/plugins/geofence/geofence.h"
#include "../../jni_utils.h"

#include <utility>

using namespace mavsdk::jni;





// ===== UploadGeofence Callback Wrapper =====
struct UploadGeofenceCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    UploadGeofenceCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_geofence_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== ClearGeofence Callback Wrapper =====
struct ClearGeofenceCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ClearGeofenceCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_geofence_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

extern "C" {

// ===== Geofence.Companion.createNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_00024Companion_createNative(
    JNIEnv* env,
    jclass clazz,
    jlong systemHandle) {

    if (!systemHandle) {
        throwMavsdkError(env, "OperationError", "Invalid system handle");
        return 0;
    }

    mavsdk_geofence_t handle = mavsdk_geofence_create(
        reinterpret_cast<mavsdk_system_t>(systemHandle)
    );

    if (!handle) {
        throwMavsdkError(env, "OperationError", "Failed to create Geofence plugin");
        return 0;
    }

    return reinterpret_cast<jlong>(handle);
}

// ===== Geofence.destroy =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_destroy(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/geofence/Geofence");
    if (!handle) return;

    mavsdk_geofence_destroy(reinterpret_cast<mavsdk_geofence_t>(handle));
}


// ===== Geofence.upload_geofenceBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_uploadGeofenceBlocking(
    JNIEnv* env,
    jobject obj,
    jobject geofence_data) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/geofence/Geofence");
    if (!handle) return MAVSDK_GEOFENCE_RESULT_UNKNOWN;

    mavsdk_geofence_geofence_data_t geofence_data_c{}; /* TODO: convert from Java object */
    mavsdk_geofence_result_t result = mavsdk_geofence_upload_geofence(
        reinterpret_cast<mavsdk_geofence_t>(handle),
        geofence_data_c    );

    return static_cast<jint>(result);
}

// ===== Geofence.upload_geofenceAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_uploadGeofenceAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject geofence_data,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/geofence/Geofence");
    if (!handle || !callback) return;

    mavsdk_geofence_geofence_data_t geofence_data_c{}; /* TODO: convert from Java object */
    auto* wrapper = new UploadGeofenceCallbackWrapper(env, callback);

    mavsdk_geofence_upload_geofence_async(
        reinterpret_cast<mavsdk_geofence_t>(handle),        geofence_data_c,        [](const mavsdk_geofence_result_t result, void* user_data) {
            auto* w = static_cast<UploadGeofenceCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Geofence.clear_geofenceBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_clearGeofenceBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/geofence/Geofence");
    if (!handle) return MAVSDK_GEOFENCE_RESULT_UNKNOWN;


    mavsdk_geofence_result_t result = mavsdk_geofence_clear_geofence(
        reinterpret_cast<mavsdk_geofence_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Geofence.clear_geofenceAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_geofence_Geofence_clearGeofenceAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/geofence/Geofence");
    if (!handle || !callback) return;


    auto* wrapper = new ClearGeofenceCallbackWrapper(env, callback);

    mavsdk_geofence_clear_geofence_async(
        reinterpret_cast<mavsdk_geofence_t>(handle),        [](const mavsdk_geofence_result_t result, void* user_data) {
            auto* w = static_cast<ClearGeofenceCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


} // extern "C"