// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/tune/tune.proto)

package io.mavsdk.kotlin.plugins.tune

import io.mavsdk.jni.plugins.tune.NativeTune
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.locks.ReentrantReadWriteLock
import kotlin.concurrent.read
import kotlin.concurrent.write

private fun Tune.TuneDescription.toNative(): NativeTune.TuneDescription =
    NativeTune.TuneDescription(songElements.map { it.value }.toIntArray(), tempo)

private fun NativeTune.TuneDescription.toKotlin(): Tune.TuneDescription =
    Tune.TuneDescription(songElements.map { Tune.SongElement.fromValue(it) }, tempo)

private class TuneNativeImpl(private val handle: Long) : TuneNative {
    // The read lock keeps `handle` alive for the duration of a native call; destroy()
    // takes the write lock, which waits for in-flight calls to finish. Readers do not
    // exclude each other, so independent calls on this plugin still run concurrently
    // and cancelling a subscription does not queue behind a slow blocking call.
    private val lifecycle = ReentrantReadWriteLock()
    @Volatile private var destroyed = false

    private inline fun <Value> withOpen(action: () -> Value): Value = lifecycle.read {
        check(!destroyed) { "Tune is closed" }
        action()
    }

    override fun playTuneAsync(tuneDescription: Tune.TuneDescription, callback: (Int) -> Unit) {
        withOpen {
            NativeTune.playTuneAsync(
                handle,
                tuneDescription.toNative(),
                NativeTune.PlayTuneCallback { result -> callback(result) },
            )
        }
    }

    override fun destroy() {
        lifecycle.write {
            if (destroyed) return
            destroyed = true
            NativeTune.destroy(handle)
        }
    }
}

internal actual fun createTuneNative(systemHandle: Long): TuneNative =
    TuneNativeImpl(NativeTune.create(systemHandle))

internal actual class TuneCallbackGuard actual constructor() {
    private val claimed = AtomicBoolean(false)

    actual fun tryClaim(): Boolean = claimed.compareAndSet(false, true)
}
