# ruff: noqa: F401
# WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
# Edits need to be made to the proto files
# (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/winch/winch.proto)
"""
Allows users to send winch actions, as well as receive status information from winch systems.
"""

import asyncio
from typing import AsyncGenerator
from mavsdk.plugins.winch import (
    Winch,
    WinchResult,
    WinchAction,
    StatusFlags,
    Status,
)


class WinchError(Exception):
    """Raised when a Winch operation fails."""

    def __init__(self, result, origin, *params):
        self._result = result
        self._origin = origin
        self._params = params

    def __str__(self):
        return f"{self._result}: '{self._result.name}'; origin: {self._origin}; params: {self._params}"


class WinchAsync:
    """
    Allows users to send winch actions, as well as receive status information from winch systems.

    Async wrapper around :class:`Winch` that mirrors the gRPC-based
    asyncio API while using the ctypes-based C library directly.
    """

    def __init__(self, system):
        self._subscription_handles: dict = {}
        self._plugin = Winch(system._system)

    async def subscribe_status(self) -> AsyncGenerator[Status, None]:
        """
        Subscribe to 'winch status' updates.

        Yields
        ------
        status : Status
             The next update
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(data, _user_data):
            loop.call_soon_threadsafe(queue.put_nowait, data)

        handle = self._plugin.subscribe_status(callback)
        self._subscription_handles[id(queue)] = handle
        try:
            while True:
                yield await queue.get()
        finally:
            if id(queue) in self._subscription_handles:
                self._subscription_handles.pop(id(queue))
                self._plugin.unsubscribe_status(handle)

    async def status(self):
        """
        Subscribe to 'winch status' updates.

        Returns
        -------
        <protoc_gen_mavsdk.name_parser.NameParser object at 0x107c58710> : Status
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.status())

    async def relax(self, instance):
        """
        Allow motor to freewheel.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.relax(instance))

    async def relative_length_control(self, instance, length_m, rate_m_s):
        """
        Wind or unwind specified length of line, optionally using specified rate.

        Parameters
        ----------
        instance : uint32_t
        length_m : float
        rate_m_s : float
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None,
            lambda: self._plugin.relative_length_control(instance, length_m, rate_m_s),
        )

    async def rate_control(self, instance, rate_m_s):
        """
        Wind or unwind line at specified rate.

        Parameters
        ----------
        instance : uint32_t
        rate_m_s : float
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None, lambda: self._plugin.rate_control(instance, rate_m_s)
        )

    async def lock(self, instance):
        """
        Perform the locking sequence to relieve motor while in the fully retracted position.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.lock(instance))

    async def deliver(self, instance):
        """
        Sequence of drop, slow down, touch down, reel up, lock.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.deliver(instance))

    async def hold(self, instance):
        """
        Engage motor and hold current position.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.hold(instance))

    async def retract(self, instance):
        """
        Return the reel to the fully retracted position.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.retract(instance))

    async def load_line(self, instance):
        """
               Load the reel with line.

        The winch will calculate the total loaded length and stop when the tension exceeds a threshold.

               Parameters
               ----------
               instance : uint32_t
               Raises
               ------
               WinchError
                   If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None, lambda: self._plugin.load_line(instance)
        )

    async def abandon_line(self, instance):
        """
        Spool out the entire length of the line.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None, lambda: self._plugin.abandon_line(instance)
        )

    async def load_payload(self, instance):
        """
        Spools out just enough to present the hook to the user to load the payload.

        Parameters
        ----------
        instance : uint32_t
        Raises
        ------
        WinchError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None, lambda: self._plugin.load_payload(instance)
        )

    def destroy(self):
        self._subscription_handles.clear()
        self._plugin.destroy()

    def __del__(self):
        self.destroy()
