// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/geofence/geofence.proto)

#ifndef CMAVSDK_GEOFENCE_H
#define CMAVSDK_GEOFENCE_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "cmavsdk/mavsdk_export.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Enable setting a geofence.
 */

// ===== Forward Declarations =====
typedef struct mavsdk_system_s *mavsdk_system_t;

// ===== Opaque Handles =====
typedef struct mavsdk_geofence_s *mavsdk_geofence_t;

// ===== Enums =====
/**
 * @brief Geofence types.
 */
typedef enum {
    /**  Type representing an inclusion fence. */
    MAVSDK_GEOFENCE_FENCE_TYPE_INCLUSION = 0,
    /**  Type representing an exclusion fence. */
    MAVSDK_GEOFENCE_FENCE_TYPE_EXCLUSION = 1,
} mavsdk_geofence_fence_type_t;


// ===== Structs =====
/**
 * @brief Point type.
 *
 * @note This struct may contain dynamically allocated memory. Always call
 *       mavsdk_geofence_point_destroy() when done to avoid memory leaks.
 */
typedef struct CMAVSDK_EXPORT {
    /**  Latitude in degrees (range: -90 to +90) */
    double latitude_deg;
    /**  Longitude in degrees (range: -180 to +180) */
    double longitude_deg;
} mavsdk_geofence_point_t;

/**
 * @brief Destroy a point struct.
 *
 * Frees all memory allocated by MAVSDK for this struct, including any
 * dynamically allocated arrays or strings. Must be called to avoid memory leaks.
 * Always call this function when done with the struct, even if it currently
 * contains no dynamic allocations.
 *
 * @param target Pointer to the struct to destroy. Can be NULL (no-op).
 */
CMAVSDK_EXPORT void mavsdk_geofence_point_destroy(
    mavsdk_geofence_point_t* target);

/**
 * @brief Destroy an array of point structs.
 *
 * Frees all memory allocated for the array and its elements, including any
 * nested dynamic allocations. Must be called to avoid memory leaks.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 * @param size Number of elements in the array.
 */
CMAVSDK_EXPORT void mavsdk_geofence_point_array_destroy(
    mavsdk_geofence_point_t** array,
    size_t size);

/**
 * @brief Polygon type.
 *
 * @note This struct may contain dynamically allocated memory. Always call
 *       mavsdk_geofence_polygon_destroy() when done to avoid memory leaks.
 */
typedef struct CMAVSDK_EXPORT {
    /**  Points defining the polygon */
    mavsdk_geofence_point_t* points;
    size_t points_size;
    /**  Fence type */
    mavsdk_geofence_fence_type_t fence_type;
} mavsdk_geofence_polygon_t;

/**
 * @brief Destroy a polygon struct.
 *
 * Frees all memory allocated by MAVSDK for this struct, including any
 * dynamically allocated arrays or strings. Must be called to avoid memory leaks.
 * Always call this function when done with the struct, even if it currently
 * contains no dynamic allocations.
 *
 * @param target Pointer to the struct to destroy. Can be NULL (no-op).
 */
CMAVSDK_EXPORT void mavsdk_geofence_polygon_destroy(
    mavsdk_geofence_polygon_t* target);

/**
 * @brief Destroy an array of polygon structs.
 *
 * Frees all memory allocated for the array and its elements, including any
 * nested dynamic allocations. Must be called to avoid memory leaks.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 * @param size Number of elements in the array.
 */
CMAVSDK_EXPORT void mavsdk_geofence_polygon_array_destroy(
    mavsdk_geofence_polygon_t** array,
    size_t size);

/**
 * @brief Circular type.
 *
 * @note This struct may contain dynamically allocated memory. Always call
 *       mavsdk_geofence_circle_destroy() when done to avoid memory leaks.
 */
typedef struct CMAVSDK_EXPORT {
    /**  Point defining the center */
    mavsdk_geofence_point_t point;
    /**  Radius of the circular fence */
    float radius;
    /**  Fence type */
    mavsdk_geofence_fence_type_t fence_type;
} mavsdk_geofence_circle_t;

/**
 * @brief Destroy a circle struct.
 *
 * Frees all memory allocated by MAVSDK for this struct, including any
 * dynamically allocated arrays or strings. Must be called to avoid memory leaks.
 * Always call this function when done with the struct, even if it currently
 * contains no dynamic allocations.
 *
 * @param target Pointer to the struct to destroy. Can be NULL (no-op).
 */
CMAVSDK_EXPORT void mavsdk_geofence_circle_destroy(
    mavsdk_geofence_circle_t* target);

/**
 * @brief Destroy an array of circle structs.
 *
 * Frees all memory allocated for the array and its elements, including any
 * nested dynamic allocations. Must be called to avoid memory leaks.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 * @param size Number of elements in the array.
 */
CMAVSDK_EXPORT void mavsdk_geofence_circle_array_destroy(
    mavsdk_geofence_circle_t** array,
    size_t size);

/**
 * @brief Geofence data type.
 *
 * @note This struct may contain dynamically allocated memory. Always call
 *       mavsdk_geofence_geofence_data_destroy() when done to avoid memory leaks.
 */
typedef struct CMAVSDK_EXPORT {
    /**  Polygon(s) representing the geofence(s) */
    mavsdk_geofence_polygon_t* polygons;
    size_t polygons_size;
    /**  Circle(s) representing the geofence(s) */
    mavsdk_geofence_circle_t* circles;
    size_t circles_size;
} mavsdk_geofence_geofence_data_t;

/**
 * @brief Destroy a geofence_data struct.
 *
 * Frees all memory allocated by MAVSDK for this struct, including any
 * dynamically allocated arrays or strings. Must be called to avoid memory leaks.
 * Always call this function when done with the struct, even if it currently
 * contains no dynamic allocations.
 *
 * @param target Pointer to the struct to destroy. Can be NULL (no-op).
 */
CMAVSDK_EXPORT void mavsdk_geofence_geofence_data_destroy(
    mavsdk_geofence_geofence_data_t* target);

/**
 * @brief Destroy an array of geofence_data structs.
 *
 * Frees all memory allocated for the array and its elements, including any
 * nested dynamic allocations. Must be called to avoid memory leaks.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 * @param size Number of elements in the array.
 */
CMAVSDK_EXPORT void mavsdk_geofence_geofence_data_array_destroy(
    mavsdk_geofence_geofence_data_t** array,
    size_t size);

/**
 * @brief Possible results returned for geofence requests.
 */
typedef enum {
    /**  Unknown result. */
    MAVSDK_GEOFENCE_RESULT_UNKNOWN = 0,
    /**  Request succeeded. */
    MAVSDK_GEOFENCE_RESULT_SUCCESS = 1,
    /**  Error. */
    MAVSDK_GEOFENCE_RESULT_ERROR = 2,
    /**  Too many objects in the geofence. */
    MAVSDK_GEOFENCE_RESULT_TOO_MANY_GEOFENCE_ITEMS = 3,
    /**  Vehicle is busy. */
    MAVSDK_GEOFENCE_RESULT_BUSY = 4,
    /**  Request timed out. */
    MAVSDK_GEOFENCE_RESULT_TIMEOUT = 5,
    /**  Invalid argument. */
    MAVSDK_GEOFENCE_RESULT_INVALID_ARGUMENT = 6,
    /**  No system connected. */
    MAVSDK_GEOFENCE_RESULT_NO_SYSTEM = 7,
} mavsdk_geofence_result_t;



// ===== Primitive Array Destroy Functions =====
/**
 * @brief Destroy an array of float.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_float_array_destroy(float** array);
/**
 * @brief Destroy an array of double.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_double_array_destroy(double** array);
/**
 * @brief Destroy an array of int32_t.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_int32t_array_destroy(int32_t** array);
/**
 * @brief Destroy an array of uint32_t.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_uint32t_array_destroy(uint32_t** array);
/**
 * @brief Destroy an array of int64_t.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_int64t_array_destroy(int64_t** array);
/**
 * @brief Destroy an array of uint64_t.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_uint64t_array_destroy(uint64_t** array);
/**
 * @brief Destroy an array of bool.
 *
 * Frees the memory allocated for the array.
 *
 * @param array Pointer to the array pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_bool_array_destroy(bool** array);

/**
 * @brief Destroy a string (char*).
 *
 * Frees the memory allocated for the string.
 *
 * @param str Pointer to the string pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_string_destroy(char** str);

/**
 * @brief Destroy a byte buffer (uint8_t*).
 *
 * Frees the memory allocated for the byte buffer.
 *
 * @param buffer Pointer to the buffer pointer. Will be set to NULL after freeing.
 */
CMAVSDK_EXPORT void mavsdk_geofence_byte_buffer_destroy(uint8_t** buffer);

// ===== Callback Typedefs =====
typedef void (*mavsdk_geofence_upload_geofence_callback_t)(const mavsdk_geofence_result_t result, void* user_data);
typedef void (*mavsdk_geofence_clear_geofence_callback_t)(const mavsdk_geofence_result_t result, void* user_data);

// ===== Geofence Creation/Destruction =====
CMAVSDK_EXPORT mavsdk_geofence_t mavsdk_geofence_create(mavsdk_system_t system);
CMAVSDK_EXPORT void mavsdk_geofence_destroy(mavsdk_geofence_t geofence);

// ===== Methods =====

/**
 * @brief Upload geofences.
 * 
 *  Polygon and Circular geofences are uploaded to a drone. Once uploaded, the geofence will remain
 *  on the drone even if a connection is lost.
 *
 * @param geofence The geofence instance.
* @param geofence_data  Circle(s) and/or Polygon(s) representing the geofence(s)
 * 
 * @param callback Function to call when new data is available.
 * @param user_data User data to pass to the callback.
 */
CMAVSDK_EXPORT void mavsdk_geofence_upload_geofence_async(
    mavsdk_geofence_t geofence,
    mavsdk_geofence_geofence_data_t geofence_data,
    mavsdk_geofence_upload_geofence_callback_t callback,
    void* user_data);


/**
 * @brief Get the current upload geofence (blocking).
 *
 * This function blocks until a value is available.
 *
 * @param telemetry The telemetry instance.
 * @param upload_geofence_out Pointer to store the result.
 */
CMAVSDK_EXPORT
mavsdk_geofence_result_t
mavsdk_geofence_upload_geofence(
    mavsdk_geofence_t geofence,
    mavsdk_geofence_geofence_data_t geofence_data);


/**
 * @brief Clear all geofences saved on the vehicle.
 *
 * @param geofence The geofence instance.
 * @param callback Function to call when new data is available.
 * @param user_data User data to pass to the callback.
 */
CMAVSDK_EXPORT void mavsdk_geofence_clear_geofence_async(
    mavsdk_geofence_t geofence,
    mavsdk_geofence_clear_geofence_callback_t callback,
    void* user_data);


/**
 * @brief Get the current clear geofence (blocking).
 *
 * This function blocks until a value is available.
 *
 * @param telemetry The telemetry instance.
 * @param clear_geofence_out Pointer to store the result.
 */
CMAVSDK_EXPORT
mavsdk_geofence_result_t
mavsdk_geofence_clear_geofence(
    mavsdk_geofence_t geofence);


#ifdef __cplusplus
}
#endif

#endif // CMAVSDK_GEOFENCE_H