// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/calibration/calibration.proto)

package io.mavsdk.kotlin.plugins.calibration

import io.mavsdk.kotlin.System
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow


class Calibration internal constructor(private val handle: Long) : AutoCloseable {

    enum class Result(val value: Int) {
        UNKNOWN(0),
        SUCCESS(1),
        NEXT(2),
        FAILED(3),
        NO_SYSTEM(4),
        CONNECTION_ERROR(5),
        BUSY(6),
        COMMAND_DENIED(7),
        TIMEOUT(8),
        CANCELLED(9),
        FAILED_ARMED(10),
        UNSUPPORTED(11),
        ;
        companion object {
            fun fromValue(v: Int): Result = entries.find { it.value == v } ?: values()[0]
        }
    }

    data class ProgressData(
        val hasProgress: Boolean,
        val progress: Float,
        val hasStatusText: Boolean,
        val statusText: String,
    )

    fun calibrateGyro(): Flow<kotlin.Result<ProgressData>> = callbackFlow {
        val callback = CalibrateGyroCallback { result, value ->
            val r = Result.fromValue(result)
            when {
                r == Result.NEXT -> trySend(kotlin.Result.success(value))
                r == Result.SUCCESS -> close()
                else -> { trySend(kotlin.Result.failure(CalibrationException(r, "calibrateGyro failed: ${r.name}"))); close() }
            }
        }
        calibrateGyroAsyncNative(callback)
        awaitClose {}
    }

    fun calibrateAccelerometer(): Flow<kotlin.Result<ProgressData>> = callbackFlow {
        val callback = CalibrateAccelerometerCallback { result, value ->
            val r = Result.fromValue(result)
            when {
                r == Result.NEXT -> trySend(kotlin.Result.success(value))
                r == Result.SUCCESS -> close()
                else -> { trySend(kotlin.Result.failure(CalibrationException(r, "calibrateAccelerometer failed: ${r.name}"))); close() }
            }
        }
        calibrateAccelerometerAsyncNative(callback)
        awaitClose {}
    }

    fun calibrateMagnetometer(): Flow<kotlin.Result<ProgressData>> = callbackFlow {
        val callback = CalibrateMagnetometerCallback { result, value ->
            val r = Result.fromValue(result)
            when {
                r == Result.NEXT -> trySend(kotlin.Result.success(value))
                r == Result.SUCCESS -> close()
                else -> { trySend(kotlin.Result.failure(CalibrationException(r, "calibrateMagnetometer failed: ${r.name}"))); close() }
            }
        }
        calibrateMagnetometerAsyncNative(callback)
        awaitClose {}
    }

    fun calibrateLevelHorizon(): Flow<kotlin.Result<ProgressData>> = callbackFlow {
        val callback = CalibrateLevelHorizonCallback { result, value ->
            val r = Result.fromValue(result)
            when {
                r == Result.NEXT -> trySend(kotlin.Result.success(value))
                r == Result.SUCCESS -> close()
                else -> { trySend(kotlin.Result.failure(CalibrationException(r, "calibrateLevelHorizon failed: ${r.name}"))); close() }
            }
        }
        calibrateLevelHorizonAsyncNative(callback)
        awaitClose {}
    }

    fun calibrateGimbalAccelerometer(): Flow<kotlin.Result<ProgressData>> = callbackFlow {
        val callback = CalibrateGimbalAccelerometerCallback { result, value ->
            val r = Result.fromValue(result)
            when {
                r == Result.NEXT -> trySend(kotlin.Result.success(value))
                r == Result.SUCCESS -> close()
                else -> { trySend(kotlin.Result.failure(CalibrationException(r, "calibrateGimbalAccelerometer failed: ${r.name}"))); close() }
            }
        }
        calibrateGimbalAccelerometerAsyncNative(callback)
        awaitClose {}
    }

    fun cancel(): Result =
        Result.fromValue(cancelBlocking())

    private fun interface CalibrateGyroCallback { fun invoke(result: Int, value: ProgressData) }
    private fun interface CalibrateAccelerometerCallback { fun invoke(result: Int, value: ProgressData) }
    private fun interface CalibrateMagnetometerCallback { fun invoke(result: Int, value: ProgressData) }
    private fun interface CalibrateLevelHorizonCallback { fun invoke(result: Int, value: ProgressData) }
    private fun interface CalibrateGimbalAccelerometerCallback { fun invoke(result: Int, value: ProgressData) }

    private external fun calibrateGyroAsyncNative(callback: CalibrateGyroCallback)
    private external fun calibrateAccelerometerAsyncNative(callback: CalibrateAccelerometerCallback)
    private external fun calibrateMagnetometerAsyncNative(callback: CalibrateMagnetometerCallback)
    private external fun calibrateLevelHorizonAsyncNative(callback: CalibrateLevelHorizonCallback)
    private external fun calibrateGimbalAccelerometerAsyncNative(callback: CalibrateGimbalAccelerometerCallback)
    private external fun cancelBlocking(): Int
    private external fun destroy()

    override fun close() {
        destroy()
    }

    class CalibrationException(
        val result: Result,
        message: String
    ) : Exception(message)

    companion object {
        fun create(system: System): Calibration {
            val handle = createNative(system.getHandle())
            return Calibration(handle).also { system.registerPlugin(it) }
        }
        private external fun createNative(systemHandle: Long): Long
    }
}