# ruff: noqa: F401
# WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
# Edits need to be made to the proto files
# (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/calibration/calibration.proto)
"""
Enable to calibrate sensors of a drone such as gyro, accelerometer, and magnetometer.
"""

import asyncio
from typing import AsyncGenerator
from pymavsdk.plugins.calibration import (
    Calibration,
    CalibrationResult,
    ProgressData,
)


class CalibrationError(Exception):
    """Raised when a Calibration operation fails."""

    def __init__(self, result, origin, *params):
        self._result = result
        self._origin = origin
        self._params = params

    def __str__(self):
        return f"{self._result}: '{self._result.name}'; origin: {self._origin}; params: {self._params}"


class CalibrationAsync:
    """
    Enable to calibrate sensors of a drone such as gyro, accelerometer, and magnetometer.

    Async wrapper around :class:`Calibration` that mirrors the gRPC-based
    asyncio API while using the ctypes-based C library directly.
    """

    def __init__(self, system):
        self._subscription_handles: dict = {}
        self._plugin = Calibration(system._system)

    async def calibrate_gyro(self) -> AsyncGenerator:
        """
        Perform gyro calibration.
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(result, data, _user_data=None):
            loop.call_soon_threadsafe(queue.put_nowait, (result, data))

        self._plugin.calibrate_gyro_async(callback)
        while True:
            result, data = await queue.get()
            yield result, data
            if result != CalibrationResult.NEXT:
                break

    async def calibrate_accelerometer(self) -> AsyncGenerator:
        """
        Perform accelerometer calibration.
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(result, data, _user_data=None):
            loop.call_soon_threadsafe(queue.put_nowait, (result, data))

        self._plugin.calibrate_accelerometer_async(callback)
        while True:
            result, data = await queue.get()
            yield result, data
            if result != CalibrationResult.NEXT:
                break

    async def calibrate_magnetometer(self) -> AsyncGenerator:
        """
        Perform magnetometer calibration.
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(result, data, _user_data=None):
            loop.call_soon_threadsafe(queue.put_nowait, (result, data))

        self._plugin.calibrate_magnetometer_async(callback)
        while True:
            result, data = await queue.get()
            yield result, data
            if result != CalibrationResult.NEXT:
                break

    async def calibrate_level_horizon(self) -> AsyncGenerator:
        """
        Perform board level horizon calibration.
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(result, data, _user_data=None):
            loop.call_soon_threadsafe(queue.put_nowait, (result, data))

        self._plugin.calibrate_level_horizon_async(callback)
        while True:
            result, data = await queue.get()
            yield result, data
            if result != CalibrationResult.NEXT:
                break

    async def calibrate_gimbal_accelerometer(self) -> AsyncGenerator:
        """
        Perform gimbal accelerometer calibration.
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(result, data, _user_data=None):
            loop.call_soon_threadsafe(queue.put_nowait, (result, data))

        self._plugin.calibrate_gimbal_accelerometer_async(callback)
        while True:
            result, data = await queue.get()
            yield result, data
            if result != CalibrationResult.NEXT:
                break

    async def cancel(self):
        """
        Cancel ongoing calibration process.

        Raises
        ------
        CalibrationError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.cancel())

    def destroy(self):
        self._subscription_handles.clear()
        self._plugin.destroy()

    def __del__(self):
        self.destroy()
