// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/log_files/log_files.proto)

#include <jni.h>
#include "cmavsdk/plugins/log_files/log_files.h"
#include "../../jni_utils.h"

#include <utility>

using namespace mavsdk::jni;





// ===== GetEntries Callback Wrapper =====
struct GetEntriesCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    GetEntriesCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(ILjava/lang/Object;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_log_files_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== DownloadLogFile Callback Wrapper =====
struct DownloadLogFileCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DownloadLogFileCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(ILio/mavsdk/kotlin/plugins/log_files/LogFiles$ProgressData;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_log_files_result_t result, const mavsdk_log_files_progress_data_t progress) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/log_files/LogFiles$ProgressData");
        if (!retClass) { return; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(F)V");
        jobject retObj = env->NewObject(retClass, retCtor            , static_cast<jfloat>(progress.progress)        );
        env->DeleteLocalRef(retClass);
        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result), retObj);
        env->DeleteLocalRef(retObj);

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

extern "C" {

// ===== LogFiles.Companion.createNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_log_1files_LogFiles_00024Companion_createNative(
    JNIEnv* env,
    jclass clazz,
    jlong systemHandle) {

    if (!systemHandle) {
        throwMavsdkError(env, "OperationError", "Invalid system handle");
        return 0;
    }

    mavsdk_log_files_t handle = mavsdk_log_files_create(
        reinterpret_cast<mavsdk_system_t>(systemHandle)
    );

    if (!handle) {
        throwMavsdkError(env, "OperationError", "Failed to create LogFiles plugin");
        return 0;
    }

    return reinterpret_cast<jlong>(handle);
}

// ===== LogFiles.destroy =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1files_LogFiles_destroy(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_files/LogFiles");
    if (!handle) return;

    mavsdk_log_files_destroy(reinterpret_cast<mavsdk_log_files_t>(handle));
}


// ===== LogFiles.get_entriesBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_log_1files_LogFiles_getEntriesBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_files/LogFiles");
    if (!handle) return {};


    mavsdk_log_files_get_entries(
        reinterpret_cast<mavsdk_log_files_t>(handle),
        nullptr, nullptr
    );
    return nullptr;
}

// ===== LogFiles.get_entriesAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1files_LogFiles_getEntriesAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_files/LogFiles");
    if (!handle || !callback) return;


    auto* wrapper = new GetEntriesCallbackWrapper(env, callback);

    mavsdk_log_files_get_entries_async(
        reinterpret_cast<mavsdk_log_files_t>(handle),        [](const mavsdk_log_files_result_t result, const mavsdk_log_files_entry_t* items, size_t count, void* user_data) {
            auto* w = static_cast<GetEntriesCallbackWrapper*>(user_data);
            (*w)(result); /* TODO: pass items/count to Java */
            delete w;
        },
        wrapper
    );
}



// ===== LogFiles.erase_all_log_filesBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_log_1files_LogFiles_eraseAllLogFilesBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_files/LogFiles");
    if (!handle) return MAVSDK_LOG_FILES_RESULT_UNKNOWN;


    mavsdk_log_files_result_t result = mavsdk_log_files_erase_all_log_files(
        reinterpret_cast<mavsdk_log_files_t>(handle)    );

    return static_cast<jint>(result);
}


} // extern "C"