# ruff: noqa: F401
# WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
# Edits need to be made to the proto files
# (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/shell/shell.proto)
"""
Allow to communicate with the vehicle's system shell.
"""

import asyncio
from typing import AsyncGenerator
from mavsdk.plugins.shell import (
    Shell,
    ShellResult,
)


class ShellError(Exception):
    """Raised when a Shell operation fails."""

    def __init__(self, result, origin, *params):
        self._result = result
        self._origin = origin
        self._params = params

    def __str__(self):
        return f"{self._result}: '{self._result.name}'; origin: {self._origin}; params: {self._params}"


class ShellAsync:
    """
    Allow to communicate with the vehicle's system shell.

    Async wrapper around :class:`Shell` that mirrors the gRPC-based
    asyncio API while using the ctypes-based C library directly.
    """

    def __init__(self, system):
        self._subscription_handles: dict = {}
        self._plugin = Shell(system._system)

    async def send(self, command):
        """
        Send a command line.

        Parameters
        ----------
        command : str
        Raises
        ------
        ShellError
            If the request fails. The error contains the reason for the failure.
        """
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, lambda: self._plugin.send(command))

    async def subscribe_receive(self) -> AsyncGenerator[str, None]:
        """
               Receive feedback from a sent command line.

        This subscription needs to be made before a command line is sent, otherwise, no response will be sent.

               Yields
               ------
                : str
                    The next update
        """
        loop = asyncio.get_running_loop()
        queue: asyncio.Queue = asyncio.Queue()

        def callback(data, _user_data):
            loop.call_soon_threadsafe(queue.put_nowait, data)

        handle = self._plugin.subscribe_receive(callback)
        self._subscription_handles[id(queue)] = handle
        try:
            while True:
                yield await queue.get()
        finally:
            if id(queue) in self._subscription_handles:
                self._subscription_handles.pop(id(queue))
                self._plugin.unsubscribe_receive(handle)

    def destroy(self):
        self._subscription_handles.clear()
        self._plugin.destroy()

    def __del__(self):
        self.destroy()
