set(
    CMAKE_POSITION_INDEPENDENT_CODE
    TRUE
    CACHE
    BOOL
    "Position independent code"
    FORCE
)

set(CMAKE_CXX_FLAGS "-fPIC" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "-fPIC" CACHE STRING "" FORCE)
set(CMAKE_Fortran_FLAGS "-fPIC" CACHE STRING "" FORCE)

list(APPEND HUNTER_TOOLCHAIN_UNDETECTABLE_ID "pic")
