// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/camera/camera.proto)

package io.mavsdk.kotlin.plugins.camera

import io.mavsdk.jni.plugins.camera.NativeCamera
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

private fun Camera.Option.toNative(): NativeCamera.Option =
    NativeCamera.Option(
        optionId,
        optionDescription
    )

private fun NativeCamera.Option.toKotlin(): Camera.Option =
    Camera.Option(
        optionId,
        optionDescription
    )

private fun Camera.Setting.toNative(): NativeCamera.Setting =
    NativeCamera.Setting(
        settingId,
        settingDescription,
        option.toNative(),
        isRange
    )

private fun NativeCamera.Setting.toKotlin(): Camera.Setting =
    Camera.Setting(
        settingId,
        settingDescription,
        option.toKotlin(),
        isRange
    )

private fun Camera.SettingOptions.toNative(): NativeCamera.SettingOptions =
    NativeCamera.SettingOptions(
        componentId,
        settingId,
        settingDescription,
        options.map { it.toNative() }.toTypedArray(),
        isRange
    )

private fun NativeCamera.SettingOptions.toKotlin(): Camera.SettingOptions =
    Camera.SettingOptions(
        componentId,
        settingId,
        settingDescription,
        options.map { it.toKotlin() },
        isRange
    )

private fun Camera.VideoStreamSettings.toNative(): NativeCamera.VideoStreamSettings =
    NativeCamera.VideoStreamSettings(
        frameRateHz,
        horizontalResolutionPix,
        verticalResolutionPix,
        bitRateBS,
        rotationDeg,
        uri,
        horizontalFovDeg
    )

private fun NativeCamera.VideoStreamSettings.toKotlin(): Camera.VideoStreamSettings =
    Camera.VideoStreamSettings(
        frameRateHz,
        horizontalResolutionPix,
        verticalResolutionPix,
        bitRateBS,
        rotationDeg,
        uri,
        horizontalFovDeg
    )

private fun Camera.VideoStreamInfo.toNative(): NativeCamera.VideoStreamInfo =
    NativeCamera.VideoStreamInfo(
        streamId,
        settings.toNative(),
        status.value,
        spectrum.value
    )

private fun NativeCamera.VideoStreamInfo.toKotlin(): Camera.VideoStreamInfo =
    Camera.VideoStreamInfo(
        streamId,
        settings.toKotlin(),
        Camera.VideoStreamStatus.fromValue(status),
        Camera.VideoStreamSpectrum.fromValue(spectrum)
    )

private fun Camera.ModeUpdate.toNative(): NativeCamera.ModeUpdate =
    NativeCamera.ModeUpdate(
        componentId,
        mode.value
    )

private fun NativeCamera.ModeUpdate.toKotlin(): Camera.ModeUpdate =
    Camera.ModeUpdate(
        componentId,
        Camera.Mode.fromValue(mode)
    )

private fun Camera.VideoStreamUpdate.toNative(): NativeCamera.VideoStreamUpdate =
    NativeCamera.VideoStreamUpdate(
        componentId,
        videoStreamInfo.toNative()
    )

private fun NativeCamera.VideoStreamUpdate.toKotlin(): Camera.VideoStreamUpdate =
    Camera.VideoStreamUpdate(
        componentId,
        videoStreamInfo.toKotlin()
    )

private fun Camera.Storage.toNative(): NativeCamera.Storage =
    NativeCamera.Storage(
        componentId,
        videoOn,
        photoIntervalOn,
        usedStorageMib,
        availableStorageMib,
        totalStorageMib,
        recordingTimeS,
        mediaFolderName,
        storageStatus.value,
        storageId,
        storageType.value
    )

private fun NativeCamera.Storage.toKotlin(): Camera.Storage =
    Camera.Storage(
        componentId,
        videoOn,
        photoIntervalOn,
        usedStorageMib,
        availableStorageMib,
        totalStorageMib,
        recordingTimeS,
        mediaFolderName,
        Camera.StorageStatus.fromValue(storageStatus),
        storageId,
        Camera.StorageType.fromValue(storageType)
    )

private fun Camera.StorageUpdate.toNative(): NativeCamera.StorageUpdate =
    NativeCamera.StorageUpdate(
        componentId,
        storage.toNative()
    )

private fun NativeCamera.StorageUpdate.toKotlin(): Camera.StorageUpdate =
    Camera.StorageUpdate(
        componentId,
        storage.toKotlin()
    )

private fun Camera.CurrentSettingsUpdate.toNative(): NativeCamera.CurrentSettingsUpdate =
    NativeCamera.CurrentSettingsUpdate(
        componentId,
        currentSettings.map { it.toNative() }.toTypedArray()
    )

private fun NativeCamera.CurrentSettingsUpdate.toKotlin(): Camera.CurrentSettingsUpdate =
    Camera.CurrentSettingsUpdate(
        componentId,
        currentSettings.map { it.toKotlin() }
    )

private fun Camera.PossibleSettingOptionsUpdate.toNative(): NativeCamera.PossibleSettingOptionsUpdate =
    NativeCamera.PossibleSettingOptionsUpdate(
        componentId,
        settingOptions.map { it.toNative() }.toTypedArray()
    )

private fun NativeCamera.PossibleSettingOptionsUpdate.toKotlin(): Camera.PossibleSettingOptionsUpdate =
    Camera.PossibleSettingOptionsUpdate(
        componentId,
        settingOptions.map { it.toKotlin() }
    )

private fun Camera.Position.toNative(): NativeCamera.Position =
    NativeCamera.Position(
        latitudeDeg,
        longitudeDeg,
        absoluteAltitudeM,
        relativeAltitudeM
    )

private fun NativeCamera.Position.toKotlin(): Camera.Position =
    Camera.Position(
        latitudeDeg,
        longitudeDeg,
        absoluteAltitudeM,
        relativeAltitudeM
    )

private fun Camera.Quaternion.toNative(): NativeCamera.Quaternion =
    NativeCamera.Quaternion(
        w,
        x,
        y,
        z
    )

private fun NativeCamera.Quaternion.toKotlin(): Camera.Quaternion =
    Camera.Quaternion(
        w,
        x,
        y,
        z
    )

private fun Camera.EulerAngle.toNative(): NativeCamera.EulerAngle =
    NativeCamera.EulerAngle(
        rollDeg,
        pitchDeg,
        yawDeg
    )

private fun NativeCamera.EulerAngle.toKotlin(): Camera.EulerAngle =
    Camera.EulerAngle(
        rollDeg,
        pitchDeg,
        yawDeg
    )

private fun Camera.CaptureInfo.toNative(): NativeCamera.CaptureInfo =
    NativeCamera.CaptureInfo(
        componentId,
        position.toNative(),
        attitudeQuaternion.toNative(),
        attitudeEulerAngle.toNative(),
        timeUtcUs,
        isSuccess,
        index,
        fileUrl
    )

private fun NativeCamera.CaptureInfo.toKotlin(): Camera.CaptureInfo =
    Camera.CaptureInfo(
        componentId,
        position.toKotlin(),
        attitudeQuaternion.toKotlin(),
        attitudeEulerAngle.toKotlin(),
        timeUtcUs,
        isSuccess,
        index,
        fileUrl
    )

private fun Camera.Information.toNative(): NativeCamera.Information =
    NativeCamera.Information(
        componentId,
        vendorName,
        modelName,
        focalLengthMm,
        horizontalSensorSizeMm,
        verticalSensorSizeMm,
        horizontalResolutionPx,
        verticalResolutionPx
    )

private fun NativeCamera.Information.toKotlin(): Camera.Information =
    Camera.Information(
        componentId,
        vendorName,
        modelName,
        focalLengthMm,
        horizontalSensorSizeMm,
        verticalSensorSizeMm,
        horizontalResolutionPx,
        verticalResolutionPx
    )

private fun Camera.CameraList.toNative(): NativeCamera.CameraList =
    NativeCamera.CameraList(
        cameras.map { it.toNative() }.toTypedArray()
    )

private fun NativeCamera.CameraList.toKotlin(): Camera.CameraList =
    Camera.CameraList(
        cameras.map { it.toKotlin() }
    )

private class CameraNativeImpl(
    private val handle: Long
) : CameraNative {
    private val activeSubscriptions = ConcurrentHashMap<Long, () -> Unit>()

    override fun takePhotoAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.takePhotoAsync(
            handle,
            componentId,
            NativeCamera.TakePhotoCallback {
                    result -> callback(result)
            }
        )
    }

    override fun startPhotoIntervalAsync(
        componentId: Int,
        intervalS: Float,
        callback: (Int) -> Unit
    ) {
        NativeCamera.startPhotoIntervalAsync(
            handle,
            componentId,
            intervalS,
            NativeCamera.StartPhotoIntervalCallback {
                    result -> callback(result)
            }
        )
    }

    override fun stopPhotoIntervalAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.stopPhotoIntervalAsync(
            handle,
            componentId,
            NativeCamera.StopPhotoIntervalCallback {
                    result -> callback(result)
            }
        )
    }

    override fun startVideoAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.startVideoAsync(
            handle,
            componentId,
            NativeCamera.StartVideoCallback {
                    result -> callback(result)
            }
        )
    }

    override fun stopVideoAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.stopVideoAsync(
            handle,
            componentId,
            NativeCamera.StopVideoCallback {
                    result -> callback(result)
            }
        )
    }

    override fun startVideoStreaming(componentId: Int, streamId: Int): Int =
        NativeCamera.startVideoStreaming(handle, componentId, streamId)

    override fun stopVideoStreaming(componentId: Int, streamId: Int): Int =
        NativeCamera.stopVideoStreaming(handle, componentId, streamId)

    override fun setModeAsync(
        componentId: Int,
        mode: Camera.Mode,
        callback: (Int) -> Unit
    ) {
        NativeCamera.setModeAsync(
            handle,
            componentId,
            mode.value,
            NativeCamera.SetModeCallback {
                    result -> callback(result)
            }
        )
    }

    override fun listPhotosAsync(
        componentId: Int,
        photosRange: Camera.PhotosRange,
        callback: (Int, List<Camera.CaptureInfo>) -> Unit
    ) {
        NativeCamera.listPhotosAsync(
            handle,
            componentId,
            photosRange.value,
            NativeCamera.ListPhotosCallback {
                    result, value -> callback(result, value.map { it.toKotlin() })
            }
        )
    }

    override fun cameraList(): Camera.CameraList {
        val value = NativeCamera.cameraList(
            handle        )
        return value.toKotlin()
    }

    override fun subscribeCameraList(
        callback: (Camera.CameraList) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeCameraList(
            handle,
            NativeCamera.CameraListCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeCameraList(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeCameraList(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun subscribeMode(
        callback: (Camera.ModeUpdate) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeMode(
            handle,
            NativeCamera.ModeCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeMode(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeMode(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun getMode(componentId: Int): Camera.Mode {
        val value = NativeCamera.getMode(
            handle, componentId        )
        return Camera.Mode.fromValue(value)
    }

    override fun subscribeVideoStreamInfo(
        callback: (Camera.VideoStreamUpdate) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeVideoStreamInfo(
            handle,
            NativeCamera.VideoStreamInfoCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeVideoStreamInfo(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeVideoStreamInfo(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun getVideoStreamInfo(componentId: Int): Camera.VideoStreamInfo {
        val value = NativeCamera.getVideoStreamInfo(
            handle, componentId        )
        return value.toKotlin()
    }

    override fun subscribeCaptureInfo(
        callback: (Camera.CaptureInfo) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeCaptureInfo(
            handle,
            NativeCamera.CaptureInfoCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeCaptureInfo(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeCaptureInfo(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun subscribeStorage(
        callback: (Camera.StorageUpdate) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeStorage(
            handle,
            NativeCamera.StorageCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeStorage(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeStorage(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun getStorage(componentId: Int): Camera.Storage {
        val value = NativeCamera.getStorage(
            handle, componentId        )
        return value.toKotlin()
    }

    override fun subscribeCurrentSettings(
        callback: (Camera.CurrentSettingsUpdate) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribeCurrentSettings(
            handle,
            NativeCamera.CurrentSettingsCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribeCurrentSettings(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeCurrentSettings(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun getCurrentSettings(componentId: Int): List<Camera.Setting> {
        val value = NativeCamera.getCurrentSettings(
            handle, componentId        )
        return value.map { it.toKotlin() }
    }

    override fun subscribePossibleSettingOptions(
        callback: (Camera.PossibleSettingOptionsUpdate) -> Unit
    ): Long {
        val subscriptionHandle = NativeCamera.subscribePossibleSettingOptions(
            handle,
            NativeCamera.PossibleSettingOptionsCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeCamera.unsubscribePossibleSettingOptions(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribePossibleSettingOptions(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun getPossibleSettingOptions(componentId: Int): List<Camera.SettingOptions> {
        val value = NativeCamera.getPossibleSettingOptions(
            handle, componentId        )
        return value.map { it.toKotlin() }
    }

    override fun setSettingAsync(
        componentId: Int,
        setting: Camera.Setting,
        callback: (Int) -> Unit
    ) {
        NativeCamera.setSettingAsync(
            handle,
            componentId,
            setting.toNative(),
            NativeCamera.SetSettingCallback {
                    result -> callback(result)
            }
        )
    }

    override fun getSettingAsync(
        componentId: Int,
        setting: Camera.Setting,
        callback: (Int, Camera.Setting) -> Unit
    ) {
        NativeCamera.getSettingAsync(
            handle,
            componentId,
            setting.toNative(),
            NativeCamera.GetSettingCallback {
                    result, value -> callback(result, value.toKotlin())
            }
        )
    }

    override fun formatStorageAsync(
        componentId: Int,
        storageId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.formatStorageAsync(
            handle,
            componentId,
            storageId,
            NativeCamera.FormatStorageCallback {
                    result -> callback(result)
            }
        )
    }

    override fun resetSettingsAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.resetSettingsAsync(
            handle,
            componentId,
            NativeCamera.ResetSettingsCallback {
                    result -> callback(result)
            }
        )
    }

    override fun zoomInStartAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.zoomInStartAsync(
            handle,
            componentId,
            NativeCamera.ZoomInStartCallback {
                    result -> callback(result)
            }
        )
    }

    override fun zoomOutStartAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.zoomOutStartAsync(
            handle,
            componentId,
            NativeCamera.ZoomOutStartCallback {
                    result -> callback(result)
            }
        )
    }

    override fun zoomStopAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.zoomStopAsync(
            handle,
            componentId,
            NativeCamera.ZoomStopCallback {
                    result -> callback(result)
            }
        )
    }

    override fun zoomRangeAsync(
        componentId: Int,
        range: Float,
        callback: (Int) -> Unit
    ) {
        NativeCamera.zoomRangeAsync(
            handle,
            componentId,
            range,
            NativeCamera.ZoomRangeCallback {
                    result -> callback(result)
            }
        )
    }

    override fun trackPointAsync(
        componentId: Int,
        pointX: Float,
        pointY: Float,
        radius: Float,
        callback: (Int) -> Unit
    ) {
        NativeCamera.trackPointAsync(
            handle,
            componentId,
            pointX,
            pointY,
            radius,
            NativeCamera.TrackPointCallback {
                    result -> callback(result)
            }
        )
    }

    override fun trackRectangleAsync(
        componentId: Int,
        topLeftX: Float,
        topLeftY: Float,
        bottomRightX: Float,
        bottomRightY: Float,
        callback: (Int) -> Unit
    ) {
        NativeCamera.trackRectangleAsync(
            handle,
            componentId,
            topLeftX,
            topLeftY,
            bottomRightX,
            bottomRightY,
            NativeCamera.TrackRectangleCallback {
                    result -> callback(result)
            }
        )
    }

    override fun trackStopAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.trackStopAsync(
            handle,
            componentId,
            NativeCamera.TrackStopCallback {
                    result -> callback(result)
            }
        )
    }

    override fun focusInStartAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.focusInStartAsync(
            handle,
            componentId,
            NativeCamera.FocusInStartCallback {
                    result -> callback(result)
            }
        )
    }

    override fun focusOutStartAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.focusOutStartAsync(
            handle,
            componentId,
            NativeCamera.FocusOutStartCallback {
                    result -> callback(result)
            }
        )
    }

    override fun focusStopAsync(
        componentId: Int,
        callback: (Int) -> Unit
    ) {
        NativeCamera.focusStopAsync(
            handle,
            componentId,
            NativeCamera.FocusStopCallback {
                    result -> callback(result)
            }
        )
    }

    override fun focusRangeAsync(
        componentId: Int,
        range: Float,
        callback: (Int) -> Unit
    ) {
        NativeCamera.focusRangeAsync(
            handle,
            componentId,
            range,
            NativeCamera.FocusRangeCallback {
                    result -> callback(result)
            }
        )
    }

    override fun destroy() {
        activeSubscriptions.keys.toList().forEach { subscriptionHandle ->
            activeSubscriptions.remove(subscriptionHandle)?.invoke()
        }
        NativeCamera.destroy(handle)
    }
}

internal actual fun createCameraNative(systemHandle: Long): CameraNative =
    CameraNativeImpl(NativeCamera.create(systemHandle))

internal actual class CameraCallbackGuard actual constructor() {
    private val claimed = AtomicBoolean(false)

    actual fun tryClaim(): Boolean = claimed.compareAndSet(false, true)
}
