// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/ftp/ftp.proto)

package io.mavsdk.kotlin.plugins.ftp

import io.mavsdk.kotlin.System
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow

class Ftp internal constructor(
    private val native: FtpNative
) : AutoCloseable {
    private var closed = false

    enum class Result(val value: Int) {
        UNKNOWN(0),
        SUCCESS(1),
        NEXT(2),
        TIMEOUT(3),
        BUSY(4),
        FILE_IO_ERROR(5),
        FILE_EXISTS(6),
        FILE_DOES_NOT_EXIST(7),
        FILE_PROTECTED(8),
        INVALID_PARAMETER(9),
        UNSUPPORTED(10),
        PROTOCOL_ERROR(11),
        NO_SYSTEM(12),
        ;

        companion object {
            fun fromValue(value: Int): Result =
                entries.find { it.value == value } ?: UNKNOWN
        }
    }

    data class ListDirectoryData(
        val dirs: List<String> = emptyList(),
        val files: List<String> = emptyList(),
    )

    data class ProgressData(
        val bytesTransferred: Int,
        val totalBytes: Int,
    )

    fun download(remoteFilePath: String, localDir: String, useBurst: Boolean): Flow<kotlin.Result<ProgressData>> =
        callbackFlow {
            native.downloadAsync(remoteFilePath, localDir, useBurst, ) { result, value ->
                val parsedResult = Result.fromValue(result)
                when {
                    parsedResult == Result.NEXT -> trySend(kotlin.Result.success(value))
                    parsedResult == Result.SUCCESS -> close()
                    else -> {
                        trySend(
                            kotlin.Result.failure(
                                FtpException(
                                    parsedResult,
                                    "download failed: ${parsedResult.name}"
                                )
                            )
                        )
                        close()
                    }
                }
            }
            awaitClose {}
        }

    fun upload(localFilePath: String, remoteDir: String): Flow<kotlin.Result<ProgressData>> =
        callbackFlow {
            native.uploadAsync(localFilePath, remoteDir, ) { result, value ->
                val parsedResult = Result.fromValue(result)
                when {
                    parsedResult == Result.NEXT -> trySend(kotlin.Result.success(value))
                    parsedResult == Result.SUCCESS -> close()
                    else -> {
                        trySend(
                            kotlin.Result.failure(
                                FtpException(
                                    parsedResult,
                                    "upload failed: ${parsedResult.name}"
                                )
                            )
                        )
                        close()
                    }
                }
            }
            awaitClose {}
        }

    suspend fun listDirectory(remoteDir: String): kotlin.Result<ListDirectoryData> =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.listDirectoryAsync(remoteDir, ) { result, value ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && callbackGuard.tryClaim()) {
                    if (parsedResult == Result.SUCCESS) {
                        continuation.resume(kotlin.Result.success(value))
                    } else {
                        continuation.resume(
                            kotlin.Result.failure(
                                FtpException(
                                    parsedResult,
                                    "listDirectory failed: ${parsedResult.name}"
                                )
                            )
                        )
                    }
                }
            }
        }

    suspend fun createDirectory(remoteDir: String): Result =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.createDirectoryAsync(remoteDir, ) { result ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && parsedResult != Result.NEXT && callbackGuard.tryClaim()) {
                    continuation.resume(parsedResult)
                }
            }
        }

    suspend fun removeDirectory(remoteDir: String): Result =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.removeDirectoryAsync(remoteDir, ) { result ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && parsedResult != Result.NEXT && callbackGuard.tryClaim()) {
                    continuation.resume(parsedResult)
                }
            }
        }

    suspend fun removeFile(remoteFilePath: String): Result =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.removeFileAsync(remoteFilePath, ) { result ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && parsedResult != Result.NEXT && callbackGuard.tryClaim()) {
                    continuation.resume(parsedResult)
                }
            }
        }

    suspend fun rename(remoteFromPath: String, remoteToPath: String): Result =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.renameAsync(remoteFromPath, remoteToPath, ) { result ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && parsedResult != Result.NEXT && callbackGuard.tryClaim()) {
                    continuation.resume(parsedResult)
                }
            }
        }

    suspend fun areFilesIdentical(localFilePath: String, remoteFilePath: String): kotlin.Result<Boolean> =
        suspendCancellableCoroutine { continuation ->
            val callbackGuard = FtpCallbackGuard()
            native.areFilesIdenticalAsync(localFilePath, remoteFilePath, ) { result, value ->
                val parsedResult = Result.fromValue(result)
                if (continuation.isActive && callbackGuard.tryClaim()) {
                    if (parsedResult == Result.SUCCESS) {
                        continuation.resume(kotlin.Result.success(value))
                    } else {
                        continuation.resume(
                            kotlin.Result.failure(
                                FtpException(
                                    parsedResult,
                                    "areFilesIdentical failed: ${parsedResult.name}"
                                )
                            )
                        )
                    }
                }
            }
        }

    fun setTargetCompid(compid: Int): Result =
        Result.fromValue(native.setTargetCompid(compid))

    override fun close() {
        if (closed) return
        closed = true
        native.destroy()
    }

    class FtpException(
        val result: Result,
        message: String
    ) : Exception(message)

    companion object {
        fun create(system: System): Ftp =
            Ftp(
                createFtpNative(system.getHandle())
            ).also { system.registerPlugin(it) }
    }
}

internal interface FtpNative {
    fun downloadAsync(remoteFilePath: String, localDir: String, useBurst: Boolean, callback: (Int, Ftp.ProgressData) -> Unit)
    fun uploadAsync(localFilePath: String, remoteDir: String, callback: (Int, Ftp.ProgressData) -> Unit)
    fun listDirectoryAsync(remoteDir: String, callback: (Int, Ftp.ListDirectoryData) -> Unit)
    fun createDirectoryAsync(remoteDir: String, callback: (Int) -> Unit)
    fun removeDirectoryAsync(remoteDir: String, callback: (Int) -> Unit)
    fun removeFileAsync(remoteFilePath: String, callback: (Int) -> Unit)
    fun renameAsync(remoteFromPath: String, remoteToPath: String, callback: (Int) -> Unit)
    fun areFilesIdenticalAsync(localFilePath: String, remoteFilePath: String, callback: (Int, Boolean) -> Unit)
    fun setTargetCompid(compid: Int): Int
    fun destroy()
}

internal expect fun createFtpNative(systemHandle: Long): FtpNative

internal expect class FtpCallbackGuard() {
    fun tryClaim(): Boolean
}
