#
# Development environment for DroneCore
#
# Author: Julian Oes <julian@oes.ch>
#

FROM ubuntu:16.04
MAINTAINER Julian Oes <julian@oes.ch>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        cmake \
        build-essential \
        colordiff \
        git \
        libcurl4-openssl-dev \
        doxygen \
        autoconf \
        libtool \
        wget \
        ca-certificates \
        autoconf \
        automake \
        python \
        autotools-dev \
        libltdl-dev \
        python-pip \
        libtinyxml2-dev \
        ruby-dev \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# We need the latest astyle version
RUN wget http://archive.ubuntu.com/ubuntu/pool/universe/a/astyle/astyle_3.0.1-1ubuntu1_amd64.deb \
    && dpkg -i astyle_3.0.1-1ubuntu1_amd64.deb \
    && rm astyle_3.0.1-1ubuntu1_amd64.deb

RUN gem install --no-ri --no-rdoc fpm;

CMD ["/bin/bash"]

WORKDIR "/root/DroneCore"
