#
# Development environment for MAVSDK based on Ubuntu 22.04.
#
# Author: Julian Oes <julian@oes.ch>
#

FROM ubuntu:22.04
MAINTAINER Julian Oes <julian@oes.ch>

ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        autoconf \
        automake \
        autotools-dev \
        build-essential \
        ca-certificates \
        ccache \
        clang-format-12 \
        cmake \
        colordiff \
        doxygen \
        git \
        golang-go \
        libcurl4-openssl-dev \
        libltdl-dev \
        libtinyxml2-dev \
        libtool \
        libz-dev \
        ninja-build \
        python3 \
        python3-pip \
        python3-future \
        ruby-dev \
        software-properties-common \
        sudo \
        wget \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN gem install --no-document fpm;

RUN wget -qO- https://github.com/ncopa/su-exec/archive/dddd1567b7c76365e1e0aac561287975020a8fad.tar.gz | tar xvz && \
    cd su-exec-* && make && mv su-exec /usr/local/bin && cd .. && rm -rf su-exec-*

# Create user with id 1001 (Jenkins docker workflow default)
RUN useradd --shell /bin/bash -u 1001 -c "" -m user

ADD /sudoers.txt /etc/sudoers
RUN chmod 440 /etc/sudoers

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

WORKDIR "/home/user/MAVSDK"
