#
# MAVSDK dev container.
#
# This also contains doxygen to generate the docs.
#
# Author: Julian Oes <julian@oes.ch>
#

FROM ubuntu:24.04
MAINTAINER Julian Oes <julian@oes.ch>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        ca-certificates \
        git \
        clang-format-18 \
        colordiff \
        doxygen \
        build-essential \
        gcc \
        cmake \
        python3 \
        python3-pip \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

WORKDIR "/home/user/MAVSDK"
