#
# Development environment for the Dronecode SDK based on Ubuntu 18.04.
#
# Author: Julian Oes <julian@oes.ch>
#

FROM ubuntu:18.04
MAINTAINER Julian Oes <julian@oes.ch>

ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        autoconf \
        automake \
        autotools-dev \
        build-essential \
        ca-certificates \
        clang-format \
        cmake \
        colordiff \
        doxygen \
        git \
        golang-go \
        libcurl4-openssl-dev \
        libltdl-dev \
        libtinyxml2-dev \
        libtool \
        libz-dev \
        ninja-build \
        python \
        python-pip \
        ruby-dev \
        software-properties-common \
        sudo \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-6.0 1000

RUN gem install --no-ri --no-rdoc fpm;

ADD /sudoers.txt /etc/sudoers
RUN chmod 440 /etc/sudoers

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

WORKDIR "/home/user/DronecodeSDK"
