FROM alpine:3.8 as builder

RUN apk update
RUN apk add build-base \
            cmake \
            curl-dev \
            git \
            go \
            linux-headers \
            perl

WORKDIR /root/mavsdk

COPY . .

RUN make BUILD_MAVSDK_SERVER=YES INSTALL_PREFIX=/root/dcsdk_install default install

FROM alpine:3.8

RUN apk update
RUN apk add libcurl \
            libgcc \
            libstdc++

COPY --from=builder /root/dcsdk_install /usr/local
COPY --from=builder /root/mavsdk/build/default/mavsdk_server/src/mavsdk_server_bin /root/mavsdk_server_bin

EXPOSE 14540/udp
ENTRYPOINT /root/mavsdk_server_bin
