#
# MAVSDK container for Ubuntu 20.04.
#
# This container includes all dependencies needed for:
# - Development
# - CI builds
# - Documentation generation
#

FROM ubuntu:20.04
LABEL maintainer="MAVSDK Team <mavsdk-discuss@googlegroups.com>"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        ca-certificates \
        git \
        build-essential \
        gcc \
        g++ \
        cmake \
        python3 \
        python3-pip \
        python3-future \
        lcov \
        ruby-dev \
        doxygen \
        colordiff \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install fpm for packaging
RUN gem install --no-document fpm

WORKDIR "/home/user/MAVSDK"
