#
# MAVSDK container for Ubuntu 20.04.
#
# This container includes all dependencies needed for:
# - Development
# - CI builds
# - Documentation generation
#

FROM ubuntu:20.04
LABEL maintainer="MAVSDK Team <mavsdk-discuss@googlegroups.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        sudo \
        ca-certificates \
        git \
        build-essential \
        gcc \
        g++ \
        python3 \
        python3-pip \
        python3-future \
        ruby-dev \
        doxygen \
        colordiff \
        lsb-release \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*


# Newer cmake
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
    | gpg --dearmor - \
    | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
    && apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
    && apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
        cmake
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install fpm for packaging
# First install a compatible version of dotenv for Ruby 2.7
RUN gem install --no-document dotenv -v 2.8.1 && \
    gem install --no-document fpm

WORKDIR "/home/user/MAVSDK"
