#
# Development environment for the Dronecode SDK based on Fedora 28.
#
# Author: Julian Oes <julian@oes.ch>
#

FROM fedora:28

MAINTAINER Julian Oes <julian@oes.ch>

RUN dnf -y install \
    autoconf \
    automake \
    ccache \
    clang \
    cmake \
    colordiff \
    doxygen \
    gcc \
    gcc-c++ \
    git \
    golang \
    libcurl-devel \
    libtool \
    make \
    ninja-build \
    python \
    redhat-rpm-config \
    rpm-build \
    ruby-devel \
    rubygems \
    sudo \
    tinyxml2-devel \
    which \
    zlib-devel \
    && dnf clean all

RUN gem install --no-ri --no-rdoc fpm;

ADD /sudoers.txt /etc/sudoers
RUN chmod 440 /etc/sudoers

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

WORKDIR "/home/user/DronecodeSDK"
