// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/manual_control/manual_control.proto)

package io.mavsdk.kotlin.plugins.manual_control

import io.mavsdk.kotlin.System
import kotlin.coroutines.resume
import kotlinx.coroutines.suspendCancellableCoroutine

class ManualControl internal constructor(private val native: ManualControlNative) : AutoCloseable {
    private var closed = false

    enum class Result(val value: Int) {
        UNKNOWN(0),
        SUCCESS(1),
        NO_SYSTEM(2),
        CONNECTION_ERROR(3),
        BUSY(4),
        COMMAND_DENIED(5),
        TIMEOUT(6),
        INPUT_OUT_OF_RANGE(7),
        INPUT_NOT_SET(8);

        companion object {
            fun fromValue(value: Int): Result = entries.find { it.value == value } ?: UNKNOWN
        }
    }

    suspend fun startPositionControl(): Result = suspendCancellableCoroutine { continuation ->
        val callbackGuard = ManualControlCallbackGuard()
        native.startPositionControlAsync() { result ->
            val parsedResult = Result.fromValue(result)
            if (continuation.isActive && true && callbackGuard.tryClaim()) {
                continuation.resume(parsedResult)
            }
        }
    }

    suspend fun startAltitudeControl(): Result = suspendCancellableCoroutine { continuation ->
        val callbackGuard = ManualControlCallbackGuard()
        native.startAltitudeControlAsync() { result ->
            val parsedResult = Result.fromValue(result)
            if (continuation.isActive && true && callbackGuard.tryClaim()) {
                continuation.resume(parsedResult)
            }
        }
    }

    fun setManualControlInput(x: Float, y: Float, z: Float, r: Float): Result =
        Result.fromValue(native.setManualControlInput(x, y, z, r))

    override fun close() {
        if (closed) return
        closed = true
        native.destroy()
    }

    class ManualControlException(val result: Result, message: String) : Exception(message)

    companion object {
        fun create(system: System): ManualControl =
            ManualControl(createManualControlNative(system.getHandle())).also {
                system.registerPlugin(it)
            }
    }
}

internal interface ManualControlNative {
    fun startPositionControlAsync(callback: (Int) -> Unit)

    fun startAltitudeControlAsync(callback: (Int) -> Unit)

    fun setManualControlInput(x: Float, y: Float, z: Float, r: Float): Int

    fun destroy()
}

internal expect fun createManualControlNative(systemHandle: Long): ManualControlNative

internal expect class ManualControlCallbackGuard() {
    fun tryClaim(): Boolean
}
