// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/tune/tune.proto)

#include <iomanip>

#include "tune_impl.h"
#include "plugins/tune/tune.h"

namespace mavsdk {

using TuneDescription = Tune::TuneDescription;

Tune::Tune(System& system) : PluginBase(), _impl{std::make_unique<TuneImpl>(system)} {}

Tune::Tune(std::shared_ptr<System> system) : PluginBase(), _impl{std::make_unique<TuneImpl>(system)}
{}

Tune::~Tune() {}

void Tune::play_tune_async(TuneDescription tune_description, const ResultCallback callback)
{
    _impl->play_tune_async(tune_description, callback);
}

Tune::Result Tune::play_tune(TuneDescription tune_description) const
{
    return _impl->play_tune(tune_description);
}

MAVSDK_PUBLIC bool operator==(const Tune::TuneDescription& lhs, const Tune::TuneDescription& rhs)
{
    return (rhs.song_elements == lhs.song_elements) && (rhs.tempo == lhs.tempo);
}

MAVSDK_PUBLIC std::ostream&
operator<<(std::ostream& str, Tune::TuneDescription const& tune_description)
{
    str << std::setprecision(15);
    str << "tune_description:" << '\n' << "{\n";
    str << "    song_elements: [";
    for (auto it = tune_description.song_elements.begin();
         it != tune_description.song_elements.end();
         ++it) {
        str << *it;
        str << (it + 1 != tune_description.song_elements.end() ? ", " : "]\n");
    }
    str << "    tempo: " << tune_description.tempo << '\n';
    str << '}';
    return str;
}

MAVSDK_PUBLIC std::string_view to_string(Tune::Result const& result)
{
    switch (result) {
        case Tune::Result::Unknown:
            return "Unknown";
        case Tune::Result::Success:
            return "Success";
        case Tune::Result::InvalidTempo:
            return "Invalid Tempo";
        case Tune::Result::TuneTooLong:
            return "Tune Too Long";
        case Tune::Result::Error:
            return "Error";
        case Tune::Result::NoSystem:
            return "No System";
        default:
            return "Unknown";
    }
}

MAVSDK_PUBLIC std::ostream& operator<<(std::ostream& str, Tune::Result const& result)
{
    return str << to_string(result);
}

MAVSDK_PUBLIC std::string_view to_string(Tune::SongElement const& song_element)
{
    switch (song_element) {
        case Tune::SongElement::StyleLegato:
            return "Style Legato";
        case Tune::SongElement::StyleNormal:
            return "Style Normal";
        case Tune::SongElement::StyleStaccato:
            return "Style Staccato";
        case Tune::SongElement::Duration1:
            return "Duration 1";
        case Tune::SongElement::Duration2:
            return "Duration 2";
        case Tune::SongElement::Duration4:
            return "Duration 4";
        case Tune::SongElement::Duration8:
            return "Duration 8";
        case Tune::SongElement::Duration16:
            return "Duration 16";
        case Tune::SongElement::Duration32:
            return "Duration 32";
        case Tune::SongElement::NoteA:
            return "Note A";
        case Tune::SongElement::NoteB:
            return "Note B";
        case Tune::SongElement::NoteC:
            return "Note C";
        case Tune::SongElement::NoteD:
            return "Note D";
        case Tune::SongElement::NoteE:
            return "Note E";
        case Tune::SongElement::NoteF:
            return "Note F";
        case Tune::SongElement::NoteG:
            return "Note G";
        case Tune::SongElement::NotePause:
            return "Note Pause";
        case Tune::SongElement::Sharp:
            return "Sharp";
        case Tune::SongElement::Flat:
            return "Flat";
        case Tune::SongElement::OctaveUp:
            return "Octave Up";
        case Tune::SongElement::OctaveDown:
            return "Octave Down";
        default:
            return "Unknown";
    }
}

MAVSDK_PUBLIC std::ostream& operator<<(std::ostream& str, Tune::SongElement const& song_element)
{
    return str << to_string(song_element);
}

} // namespace mavsdk