// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/geofence/geofence.proto)

package io.mavsdk.kotlin.plugins.geofence

import io.mavsdk.jni.plugins.geofence.NativeGeofence
import java.util.concurrent.atomic.AtomicBoolean

private fun Geofence.Point.toNative(): NativeGeofence.Point =
    NativeGeofence.Point(
        latitudeDeg,
        longitudeDeg
    )

private fun NativeGeofence.Point.toKotlin(): Geofence.Point =
    Geofence.Point(
        latitudeDeg,
        longitudeDeg
    )

private fun Geofence.Polygon.toNative(): NativeGeofence.Polygon =
    NativeGeofence.Polygon(
        points.map { it.toNative() }.toTypedArray(),
        fenceType.value
    )

private fun NativeGeofence.Polygon.toKotlin(): Geofence.Polygon =
    Geofence.Polygon(
        points.map { it.toKotlin() },
        Geofence.FenceType.fromValue(fenceType)
    )

private fun Geofence.Circle.toNative(): NativeGeofence.Circle =
    NativeGeofence.Circle(
        point.toNative(),
        radius,
        fenceType.value
    )

private fun NativeGeofence.Circle.toKotlin(): Geofence.Circle =
    Geofence.Circle(
        point.toKotlin(),
        radius,
        Geofence.FenceType.fromValue(fenceType)
    )

private fun Geofence.GeofenceData.toNative(): NativeGeofence.GeofenceData =
    NativeGeofence.GeofenceData(
        polygons.map { it.toNative() }.toTypedArray(),
        circles.map { it.toNative() }.toTypedArray()
    )

private fun NativeGeofence.GeofenceData.toKotlin(): Geofence.GeofenceData =
    Geofence.GeofenceData(
        polygons.map { it.toKotlin() },
        circles.map { it.toKotlin() }
    )

private class GeofenceNativeImpl(
    private val handle: Long
) : GeofenceNative {
    override fun uploadGeofenceAsync(
        geofenceData: Geofence.GeofenceData,
        callback: (Int) -> Unit
    ) {
        NativeGeofence.uploadGeofenceAsync(
            handle,
            geofenceData.toNative(),
            NativeGeofence.UploadGeofenceCallback {
                    result -> callback(result)
            }
        )
    }

    override fun clearGeofenceAsync(
        callback: (Int) -> Unit
    ) {
        NativeGeofence.clearGeofenceAsync(
            handle,
            NativeGeofence.ClearGeofenceCallback {
                    result -> callback(result)
            }
        )
    }

    override fun destroy() {
        NativeGeofence.destroy(handle)
    }
}

internal actual fun createGeofenceNative(systemHandle: Long): GeofenceNative =
    GeofenceNativeImpl(NativeGeofence.create(systemHandle))

internal actual class GeofenceCallbackGuard actual constructor() {
    private val claimed = AtomicBoolean(false)

    actual fun tryClaim(): Boolean = claimed.compareAndSet(false, true)
}
