// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see
// https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/server_utility/server_utility.proto)

package io.mavsdk.kotlin.plugins.server_utility

import io.mavsdk.jni.plugins.server_utility.NativeServerUtility

private class ServerUtilityNativeImpl(private val handle: Long) : ServerUtilityNative {
    override fun sendStatusText(type: ServerUtility.StatusTextType, text: String): Int =
        NativeServerUtility.sendStatusText(handle, type.value, text)

    override fun destroy() {
        NativeServerUtility.destroy(handle)
    }
}

internal actual fun createServerUtilityNative(systemHandle: Long): ServerUtilityNative =
    ServerUtilityNativeImpl(NativeServerUtility.create(systemHandle))
