// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/shell/shell.proto)

#include "shell.h"

#include <mavsdk/plugins/shell/shell.h>
#include <cstring>
#include <vector>

// ===== C++ to C Type Conversions =====

static mavsdk_shell_result_t
translate_result(mavsdk::Shell::Result cpp_result) {
    switch(cpp_result) {
        case mavsdk::Shell::Result::Unknown:
            return MAVSDK_SHELL_RESULT_UNKNOWN;
        case mavsdk::Shell::Result::Success:
            return MAVSDK_SHELL_RESULT_SUCCESS;
        case mavsdk::Shell::Result::NoSystem:
            return MAVSDK_SHELL_RESULT_NO_SYSTEM;
        case mavsdk::Shell::Result::ConnectionError:
            return MAVSDK_SHELL_RESULT_CONNECTION_ERROR;
        case mavsdk::Shell::Result::NoResponse:
            return MAVSDK_SHELL_RESULT_NO_RESPONSE;
        case mavsdk::Shell::Result::Busy:
            return MAVSDK_SHELL_RESULT_BUSY;
    }
}




// ===== Primitive Array Destroy Functions =====
void mavsdk_shell_float_array_destroy(float** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_double_array_destroy(double** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_int32t_array_destroy(int32_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_uint32t_array_destroy(uint32_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_int64t_array_destroy(int64_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_uint64t_array_destroy(uint64_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_shell_bool_array_destroy(bool** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}


void mavsdk_shell_string_destroy(char** str) {
    if (!str || !*str) return;
    free(*str);
    *str = nullptr;
}

void mavsdk_shell_byte_buffer_destroy(uint8_t** buffer) {
    if (!buffer || !*buffer) return;
    delete[] *buffer;
    *buffer = nullptr;
}

// ===== Shell Wrapper =====

struct mavsdk_shell_wrapper {
    std::shared_ptr<mavsdk::Shell> cpp_plugin;
};

mavsdk_shell_t
mavsdk_shell_create(mavsdk_system_t system) {
    if (system == nullptr) {
        return nullptr;
    }

    auto wrapper = new mavsdk_shell_wrapper();
    auto system_ptr = reinterpret_cast<std::shared_ptr<mavsdk::System>*>(system);
    wrapper->cpp_plugin = std::make_shared<mavsdk::Shell>(*system_ptr);

    return reinterpret_cast<mavsdk_shell_t>(wrapper);
}

void mavsdk_shell_destroy(mavsdk_shell_t shell) {
    if (shell == nullptr) {
        return;
    }

    auto wrapper = reinterpret_cast<mavsdk_shell_wrapper*>(shell);
    delete wrapper;
}

// ===== Method Implementations =====


// Send sync
mavsdk_shell_result_t
mavsdk_shell_send(
    mavsdk_shell_t shell,
    char* command)
{
    auto wrapper = reinterpret_cast<mavsdk_shell_wrapper*>(shell);

    auto ret_value = wrapper->cpp_plugin->send(        command);

    return translate_result(ret_value);
}

// Receive async
mavsdk_shell_receive_handle_t mavsdk_shell_subscribe_receive(
    mavsdk_shell_t shell,
    mavsdk_shell_receive_callback_t callback,
    void* user_data)
{
    auto wrapper = reinterpret_cast<mavsdk_shell_wrapper*>(shell);

    auto cpp_handle =    wrapper->cpp_plugin->subscribe_receive(
        [callback, user_data](
            const std::string& value) {
                if (callback) {
                    callback(
                        strdup(value.c_str()),
                        user_data);
                }
        });

    auto handle_wrapper = new mavsdk::Shell::ReceiveHandle(std::move(cpp_handle));
    return reinterpret_cast<mavsdk_shell_receive_handle_t>(handle_wrapper);
}

void mavsdk_shell_unsubscribe_receive(
    mavsdk_shell_t shell,
    mavsdk_shell_receive_handle_t handle)
{
    if (handle) {
        auto wrapper = reinterpret_cast<mavsdk_shell_wrapper*>(shell);
        auto cpp_handle = reinterpret_cast<mavsdk::Shell::ReceiveHandle*>(handle);
        wrapper->cpp_plugin->unsubscribe_receive(std::move(*cpp_handle));
        delete cpp_handle;
    }
}

