FROM mcr.microsoft.com/devcontainers/cpp:1-debian-12

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        python3 \
        python3-pip \
        python3-future \
        python3-tqdm