// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/offboard/offboard.proto)

#include "offboard.h"

#include <mavsdk/plugins/offboard/offboard.h>
#include <cstring>
#include <vector>

// ===== C++ to C Type Conversions =====

static mavsdk_offboard_result_t
translate_result(mavsdk::Offboard::Result cpp_result) {
    switch(cpp_result) {
        case mavsdk::Offboard::Result::Unknown:
            return MAVSDK_OFFBOARD_RESULT_UNKNOWN;
        case mavsdk::Offboard::Result::Success:
            return MAVSDK_OFFBOARD_RESULT_SUCCESS;
        case mavsdk::Offboard::Result::NoSystem:
            return MAVSDK_OFFBOARD_RESULT_NO_SYSTEM;
        case mavsdk::Offboard::Result::ConnectionError:
            return MAVSDK_OFFBOARD_RESULT_CONNECTION_ERROR;
        case mavsdk::Offboard::Result::Busy:
            return MAVSDK_OFFBOARD_RESULT_BUSY;
        case mavsdk::Offboard::Result::CommandDenied:
            return MAVSDK_OFFBOARD_RESULT_COMMAND_DENIED;
        case mavsdk::Offboard::Result::Timeout:
            return MAVSDK_OFFBOARD_RESULT_TIMEOUT;
        case mavsdk::Offboard::Result::NoSetpointSet:
            return MAVSDK_OFFBOARD_RESULT_NO_SETPOINT_SET;
        case mavsdk::Offboard::Result::Failed:
            return MAVSDK_OFFBOARD_RESULT_FAILED;
    }
}



static mavsdk::Offboard::Attitude
translate_Attitude_from_c(const mavsdk_offboard_Attitude_t& c_struct) {
    mavsdk::Offboard::Attitude cpp_struct{};
    cpp_struct.roll_deg = c_struct.roll_deg;
    cpp_struct.pitch_deg = c_struct.pitch_deg;
    cpp_struct.yaw_deg = c_struct.yaw_deg;
    cpp_struct.thrust_value = c_struct.thrust_value;
    return cpp_struct;
}

static mavsdk_offboard_Attitude_t
translate_Attitude_to_c(const mavsdk::Offboard::Attitude& cpp_struct) {
    mavsdk_offboard_Attitude_t c_struct{};
    c_struct.roll_deg = cpp_struct.roll_deg;
    c_struct.pitch_deg = cpp_struct.pitch_deg;
    c_struct.yaw_deg = cpp_struct.yaw_deg;
    c_struct.thrust_value = cpp_struct.thrust_value;
    return c_struct;
}

void mavsdk_offboard_Attitude_destroy(
    mavsdk_offboard_Attitude_t* target) {
    if (!target) return;
}

void mavsdk_offboard_Attitude_array_destroy(
    mavsdk_offboard_Attitude_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_Attitude_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::ActuatorControlGroup
translate_ActuatorControlGroup_from_c(const mavsdk_offboard_ActuatorControlGroup_t& c_struct) {
    mavsdk::Offboard::ActuatorControlGroup cpp_struct{};
    cpp_struct.controls.assign(
        c_struct.controls,
        c_struct.controls + c_struct.controls_size);
    return cpp_struct;
}

static mavsdk_offboard_ActuatorControlGroup_t
translate_ActuatorControlGroup_to_c(const mavsdk::Offboard::ActuatorControlGroup& cpp_struct) {
    mavsdk_offboard_ActuatorControlGroup_t c_struct{};
    c_struct.controls_size = cpp_struct.controls.size();
    c_struct.controls = new float[c_struct.controls_size];
    std::copy(cpp_struct.controls.begin(), cpp_struct.controls.end(), c_struct.controls);
    return c_struct;
}

void mavsdk_offboard_ActuatorControlGroup_destroy(
    mavsdk_offboard_ActuatorControlGroup_t* target) {
    if (!target) return;
    if (target->controls) {
        delete[] target->controls;
        target->controls = nullptr;
        target->controls_size = 0;
    }
}

void mavsdk_offboard_ActuatorControlGroup_array_destroy(
    mavsdk_offboard_ActuatorControlGroup_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_ActuatorControlGroup_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::ActuatorControl
translate_ActuatorControl_from_c(const mavsdk_offboard_ActuatorControl_t& c_struct) {
    mavsdk::Offboard::ActuatorControl cpp_struct{};
    cpp_struct.groups.reserve(c_struct.groups_size);
    for (size_t i = 0; i < c_struct.groups_size; i++) {
        cpp_struct.groups.push_back(
            translate_ActuatorControlGroup_from_c(c_struct.groups[i]));
    }
    return cpp_struct;
}

static mavsdk_offboard_ActuatorControl_t
translate_ActuatorControl_to_c(const mavsdk::Offboard::ActuatorControl& cpp_struct) {
    mavsdk_offboard_ActuatorControl_t c_struct{};
    c_struct.groups_size = cpp_struct.groups.size();
    c_struct.groups = new mavsdk_offboard_ActuatorControlGroup_t[c_struct.groups_size];
    for (size_t i = 0; i < c_struct.groups_size; i++) {
        c_struct.groups[i] = translate_ActuatorControlGroup_to_c(cpp_struct.groups[i]);
    }
    return c_struct;
}

void mavsdk_offboard_ActuatorControl_destroy(
    mavsdk_offboard_ActuatorControl_t* target) {
    if (!target) return;
    if (target->groups) {
        for (size_t i = 0; i < target->groups_size; i++) {
            mavsdk_offboard_ActuatorControlGroup_destroy(&target->groups[i]);
        }
        delete[] target->groups;
        target->groups = nullptr;
        target->groups_size = 0;
    }
}

void mavsdk_offboard_ActuatorControl_array_destroy(
    mavsdk_offboard_ActuatorControl_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_ActuatorControl_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::AttitudeRate
translate_AttitudeRate_from_c(const mavsdk_offboard_AttitudeRate_t& c_struct) {
    mavsdk::Offboard::AttitudeRate cpp_struct{};
    cpp_struct.roll_deg_s = c_struct.roll_deg_s;
    cpp_struct.pitch_deg_s = c_struct.pitch_deg_s;
    cpp_struct.yaw_deg_s = c_struct.yaw_deg_s;
    cpp_struct.thrust_value = c_struct.thrust_value;
    return cpp_struct;
}

static mavsdk_offboard_AttitudeRate_t
translate_AttitudeRate_to_c(const mavsdk::Offboard::AttitudeRate& cpp_struct) {
    mavsdk_offboard_AttitudeRate_t c_struct{};
    c_struct.roll_deg_s = cpp_struct.roll_deg_s;
    c_struct.pitch_deg_s = cpp_struct.pitch_deg_s;
    c_struct.yaw_deg_s = cpp_struct.yaw_deg_s;
    c_struct.thrust_value = cpp_struct.thrust_value;
    return c_struct;
}

void mavsdk_offboard_AttitudeRate_destroy(
    mavsdk_offboard_AttitudeRate_t* target) {
    if (!target) return;
}

void mavsdk_offboard_AttitudeRate_array_destroy(
    mavsdk_offboard_AttitudeRate_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_AttitudeRate_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::PositionNedYaw
translate_PositionNedYaw_from_c(const mavsdk_offboard_PositionNedYaw_t& c_struct) {
    mavsdk::Offboard::PositionNedYaw cpp_struct{};
    cpp_struct.north_m = c_struct.north_m;
    cpp_struct.east_m = c_struct.east_m;
    cpp_struct.down_m = c_struct.down_m;
    cpp_struct.yaw_deg = c_struct.yaw_deg;
    return cpp_struct;
}

static mavsdk_offboard_PositionNedYaw_t
translate_PositionNedYaw_to_c(const mavsdk::Offboard::PositionNedYaw& cpp_struct) {
    mavsdk_offboard_PositionNedYaw_t c_struct{};
    c_struct.north_m = cpp_struct.north_m;
    c_struct.east_m = cpp_struct.east_m;
    c_struct.down_m = cpp_struct.down_m;
    c_struct.yaw_deg = cpp_struct.yaw_deg;
    return c_struct;
}

void mavsdk_offboard_PositionNedYaw_destroy(
    mavsdk_offboard_PositionNedYaw_t* target) {
    if (!target) return;
}

void mavsdk_offboard_PositionNedYaw_array_destroy(
    mavsdk_offboard_PositionNedYaw_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_PositionNedYaw_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::PositionGlobalYaw::AltitudeType
translate_PositionGlobalYaw_AltitudeType_from_c(mavsdk_offboard_PositionGlobalYaw_AltitudeType_t c_enum) {
    switch(c_enum) {
        case MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_REL_HOME:
            return mavsdk::Offboard::PositionGlobalYaw::AltitudeType::RelHome;
        case MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_AMSL:
            return mavsdk::Offboard::PositionGlobalYaw::AltitudeType::Amsl;
        case MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_AGL:
            return mavsdk::Offboard::PositionGlobalYaw::AltitudeType::Agl;
    }
    return mavsdk::Offboard::PositionGlobalYaw::AltitudeType::RelHome;
}


static mavsdk::Offboard::PositionGlobalYaw
translate_PositionGlobalYaw_from_c(const mavsdk_offboard_PositionGlobalYaw_t& c_struct) {
    mavsdk::Offboard::PositionGlobalYaw cpp_struct{};
    cpp_struct.lat_deg = c_struct.lat_deg;
    cpp_struct.lon_deg = c_struct.lon_deg;
    cpp_struct.alt_m = c_struct.alt_m;
    cpp_struct.yaw_deg = c_struct.yaw_deg;
    cpp_struct.altitude_type = translate_PositionGlobalYaw_AltitudeType_from_c(c_struct.altitude_type);
    return cpp_struct;
}


static mavsdk_offboard_PositionGlobalYaw_AltitudeType_t
translate_PositionGlobalYaw_AltitudeType_to_c(mavsdk::Offboard::PositionGlobalYaw::AltitudeType cpp_enum) {
    switch(cpp_enum) {
        case mavsdk::Offboard::PositionGlobalYaw::AltitudeType::RelHome:
            return MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_REL_HOME;
        case mavsdk::Offboard::PositionGlobalYaw::AltitudeType::Amsl:
            return MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_AMSL;
        case mavsdk::Offboard::PositionGlobalYaw::AltitudeType::Agl:
            return MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_AGL;
    }
    return MAVSDK_OFFBOARD_POSITION_GLOBAL_YAW_ALTITUDE_TYPE_REL_HOME;
}

static mavsdk_offboard_PositionGlobalYaw_t
translate_PositionGlobalYaw_to_c(const mavsdk::Offboard::PositionGlobalYaw& cpp_struct) {
    mavsdk_offboard_PositionGlobalYaw_t c_struct{};
    c_struct.lat_deg = cpp_struct.lat_deg;
    c_struct.lon_deg = cpp_struct.lon_deg;
    c_struct.alt_m = cpp_struct.alt_m;
    c_struct.yaw_deg = cpp_struct.yaw_deg;
    c_struct.altitude_type = translate_PositionGlobalYaw_AltitudeType_to_c(cpp_struct.altitude_type);
    return c_struct;
}

void mavsdk_offboard_PositionGlobalYaw_destroy(
    mavsdk_offboard_PositionGlobalYaw_t* target) {
    if (!target) return;
}

void mavsdk_offboard_PositionGlobalYaw_array_destroy(
    mavsdk_offboard_PositionGlobalYaw_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_PositionGlobalYaw_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::VelocityBodyYawspeed
translate_VelocityBodyYawspeed_from_c(const mavsdk_offboard_VelocityBodyYawspeed_t& c_struct) {
    mavsdk::Offboard::VelocityBodyYawspeed cpp_struct{};
    cpp_struct.forward_m_s = c_struct.forward_m_s;
    cpp_struct.right_m_s = c_struct.right_m_s;
    cpp_struct.down_m_s = c_struct.down_m_s;
    cpp_struct.yawspeed_deg_s = c_struct.yawspeed_deg_s;
    return cpp_struct;
}

static mavsdk_offboard_VelocityBodyYawspeed_t
translate_VelocityBodyYawspeed_to_c(const mavsdk::Offboard::VelocityBodyYawspeed& cpp_struct) {
    mavsdk_offboard_VelocityBodyYawspeed_t c_struct{};
    c_struct.forward_m_s = cpp_struct.forward_m_s;
    c_struct.right_m_s = cpp_struct.right_m_s;
    c_struct.down_m_s = cpp_struct.down_m_s;
    c_struct.yawspeed_deg_s = cpp_struct.yawspeed_deg_s;
    return c_struct;
}

void mavsdk_offboard_VelocityBodyYawspeed_destroy(
    mavsdk_offboard_VelocityBodyYawspeed_t* target) {
    if (!target) return;
}

void mavsdk_offboard_VelocityBodyYawspeed_array_destroy(
    mavsdk_offboard_VelocityBodyYawspeed_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_VelocityBodyYawspeed_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::VelocityNedYaw
translate_VelocityNedYaw_from_c(const mavsdk_offboard_VelocityNedYaw_t& c_struct) {
    mavsdk::Offboard::VelocityNedYaw cpp_struct{};
    cpp_struct.north_m_s = c_struct.north_m_s;
    cpp_struct.east_m_s = c_struct.east_m_s;
    cpp_struct.down_m_s = c_struct.down_m_s;
    cpp_struct.yaw_deg = c_struct.yaw_deg;
    return cpp_struct;
}

static mavsdk_offboard_VelocityNedYaw_t
translate_VelocityNedYaw_to_c(const mavsdk::Offboard::VelocityNedYaw& cpp_struct) {
    mavsdk_offboard_VelocityNedYaw_t c_struct{};
    c_struct.north_m_s = cpp_struct.north_m_s;
    c_struct.east_m_s = cpp_struct.east_m_s;
    c_struct.down_m_s = cpp_struct.down_m_s;
    c_struct.yaw_deg = cpp_struct.yaw_deg;
    return c_struct;
}

void mavsdk_offboard_VelocityNedYaw_destroy(
    mavsdk_offboard_VelocityNedYaw_t* target) {
    if (!target) return;
}

void mavsdk_offboard_VelocityNedYaw_array_destroy(
    mavsdk_offboard_VelocityNedYaw_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_VelocityNedYaw_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}


static mavsdk::Offboard::AccelerationNed
translate_AccelerationNed_from_c(const mavsdk_offboard_AccelerationNed_t& c_struct) {
    mavsdk::Offboard::AccelerationNed cpp_struct{};
    cpp_struct.north_m_s2 = c_struct.north_m_s2;
    cpp_struct.east_m_s2 = c_struct.east_m_s2;
    cpp_struct.down_m_s2 = c_struct.down_m_s2;
    return cpp_struct;
}

static mavsdk_offboard_AccelerationNed_t
translate_AccelerationNed_to_c(const mavsdk::Offboard::AccelerationNed& cpp_struct) {
    mavsdk_offboard_AccelerationNed_t c_struct{};
    c_struct.north_m_s2 = cpp_struct.north_m_s2;
    c_struct.east_m_s2 = cpp_struct.east_m_s2;
    c_struct.down_m_s2 = cpp_struct.down_m_s2;
    return c_struct;
}

void mavsdk_offboard_AccelerationNed_destroy(
    mavsdk_offboard_AccelerationNed_t* target) {
    if (!target) return;
}

void mavsdk_offboard_AccelerationNed_array_destroy(
    mavsdk_offboard_AccelerationNed_t** array,
    size_t size) {
    if (!array || !*array) return;

    for (size_t i = 0; i < size; i++) {
        mavsdk_offboard_AccelerationNed_destroy(&(*array)[i]);
    }

    delete[] *array;
    *array = nullptr;
}



// ===== Primitive Array Destroy Functions =====
void mavsdk_offboard_float_array_destroy(float** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_double_array_destroy(double** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_int32t_array_destroy(int32_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_uint32t_array_destroy(uint32_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_int64t_array_destroy(int64_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_uint64t_array_destroy(uint64_t** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}

void mavsdk_offboard_bool_array_destroy(bool** array) {
    if (!array || !*array) return;
    delete[] *array;
    *array = nullptr;
}


void mavsdk_offboard_string_destroy(char** str) {
    if (!str || !*str) return;
    free(*str);
    *str = nullptr;
}

void mavsdk_offboard_byte_buffer_destroy(uint8_t** buffer) {
    if (!buffer || !*buffer) return;
    delete[] *buffer;
    *buffer = nullptr;
}

// ===== Offboard Wrapper =====

struct mavsdk_offboard_wrapper {
    std::shared_ptr<mavsdk::Offboard> cpp_plugin;
};

mavsdk_offboard_t
mavsdk_offboard_create(mavsdk_system_t system) {
    if (system == nullptr) {
        return nullptr;
    }

    auto wrapper = new mavsdk_offboard_wrapper();
    auto system_ptr = static_cast<std::shared_ptr<mavsdk::System>*>(system);
    wrapper->cpp_plugin = std::make_shared<mavsdk::Offboard>(*system_ptr);

    return wrapper;
}

void mavsdk_offboard_destroy(mavsdk_offboard_t offboard) {
    if (offboard == nullptr) {
        return;
    }

    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);
    delete wrapper;
}

// ===== Method Implementations =====

// Start async
void mavsdk_offboard_start_async(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_start_callback_t callback,
    void* user_data)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    wrapper->cpp_plugin->start_async(
        [callback, user_data](
            mavsdk::Offboard::Result result) {
                if (callback) {
                    callback(
                        translate_result(result),
                        user_data);
                }
        });
}


// Start sync
mavsdk_offboard_result_t
mavsdk_offboard_start(
    mavsdk_offboard_t offboard)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->start();

    return translate_result(ret_value);
}

// Stop async
void mavsdk_offboard_stop_async(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_stop_callback_t callback,
    void* user_data)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    wrapper->cpp_plugin->stop_async(
        [callback, user_data](
            mavsdk::Offboard::Result result) {
                if (callback) {
                    callback(
                        translate_result(result),
                        user_data);
                }
        });
}


// Stop sync
mavsdk_offboard_result_t
mavsdk_offboard_stop(
    mavsdk_offboard_t offboard)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->stop();

    return translate_result(ret_value);
}


// IsActive sync
void
mavsdk_offboard_is_active(
    mavsdk_offboard_t offboard,
    bool* is_active_out)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->is_active();

    *is_active_out = ret_value;
}


// SetAttitude sync
mavsdk_offboard_result_t
mavsdk_offboard_set_attitude(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_Attitude_t attitude)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_attitude(        translate_Attitude_from_c(attitude));

    return translate_result(ret_value);
}


// SetActuatorControl sync
mavsdk_offboard_result_t
mavsdk_offboard_set_actuator_control(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_ActuatorControl_t actuator_control)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_actuator_control(        translate_ActuatorControl_from_c(actuator_control));

    return translate_result(ret_value);
}


// SetAttitudeRate sync
mavsdk_offboard_result_t
mavsdk_offboard_set_attitude_rate(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_AttitudeRate_t attitude_rate)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_attitude_rate(        translate_AttitudeRate_from_c(attitude_rate));

    return translate_result(ret_value);
}


// SetPositionNed sync
mavsdk_offboard_result_t
mavsdk_offboard_set_position_ned(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_PositionNedYaw_t position_ned_yaw)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_position_ned(        translate_PositionNedYaw_from_c(position_ned_yaw));

    return translate_result(ret_value);
}


// SetPositionGlobal sync
mavsdk_offboard_result_t
mavsdk_offboard_set_position_global(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_PositionGlobalYaw_t position_global_yaw)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_position_global(        translate_PositionGlobalYaw_from_c(position_global_yaw));

    return translate_result(ret_value);
}


// SetVelocityBody sync
mavsdk_offboard_result_t
mavsdk_offboard_set_velocity_body(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_VelocityBodyYawspeed_t velocity_body_yawspeed)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_velocity_body(        translate_VelocityBodyYawspeed_from_c(velocity_body_yawspeed));

    return translate_result(ret_value);
}


// SetVelocityNed sync
mavsdk_offboard_result_t
mavsdk_offboard_set_velocity_ned(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_VelocityNedYaw_t velocity_ned_yaw)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_velocity_ned(        translate_VelocityNedYaw_from_c(velocity_ned_yaw));

    return translate_result(ret_value);
}


// SetPositionVelocityNed sync
mavsdk_offboard_result_t
mavsdk_offboard_set_position_velocity_ned(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_PositionNedYaw_t position_ned_yaw,
    mavsdk_offboard_VelocityNedYaw_t velocity_ned_yaw)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_position_velocity_ned(        translate_PositionNedYaw_from_c(position_ned_yaw),        translate_VelocityNedYaw_from_c(velocity_ned_yaw));

    return translate_result(ret_value);
}


// SetPositionVelocityAccelerationNed sync
mavsdk_offboard_result_t
mavsdk_offboard_set_position_velocity_acceleration_ned(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_PositionNedYaw_t position_ned_yaw,
    mavsdk_offboard_VelocityNedYaw_t velocity_ned_yaw,
    mavsdk_offboard_AccelerationNed_t acceleration_ned)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_position_velocity_acceleration_ned(        translate_PositionNedYaw_from_c(position_ned_yaw),        translate_VelocityNedYaw_from_c(velocity_ned_yaw),        translate_AccelerationNed_from_c(acceleration_ned));

    return translate_result(ret_value);
}


// SetAccelerationNed sync
mavsdk_offboard_result_t
mavsdk_offboard_set_acceleration_ned(
    mavsdk_offboard_t offboard,
    mavsdk_offboard_AccelerationNed_t acceleration_ned)
{
    auto wrapper = static_cast<mavsdk_offboard_wrapper*>(offboard);

    auto ret_value = wrapper->cpp_plugin->set_acceleration_ned(        translate_AccelerationNed_from_c(acceleration_ned));

    return translate_result(ret_value);
}
