// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/gripper/gripper.proto)

package io.mavsdk.kotlin.plugins.gripper

import io.mavsdk.jni.plugins.gripper.NativeGripper
import java.util.concurrent.atomic.AtomicBoolean

private class GripperNativeImpl(private val handle: Long) : GripperNative {
    override fun grabAsync(instance: Int, callback: (Int) -> Unit) {
        NativeGripper.grabAsync(
            handle,
            instance,
            NativeGripper.GrabCallback { result -> callback(result) },
        )
    }

    override fun releaseAsync(instance: Int, callback: (Int) -> Unit) {
        NativeGripper.releaseAsync(
            handle,
            instance,
            NativeGripper.ReleaseCallback { result -> callback(result) },
        )
    }

    override fun destroy() {
        NativeGripper.destroy(handle)
    }
}

internal actual fun createGripperNative(systemHandle: Long): GripperNative =
    GripperNativeImpl(NativeGripper.create(systemHandle))

internal actual class GripperCallbackGuard actual constructor() {
    private val claimed = AtomicBoolean(false)

    actual fun tryClaim(): Boolean = claimed.compareAndSet(false, true)
}
