// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/info/info.proto)

package io.mavsdk.jni.plugins.info;

/**
 * Raw JNI contract for the Info C API.
 *
 * <p>This package is an internal transport boundary. Handles, result codes, and enum values are
 * deliberately represented by primitive values; higher-level APIs provide ownership and result
 * semantics.
 */
public final class NativeInfo {
    private NativeInfo() {}

    public static final class FlightInfo {
        public final int timeBootMs;
        public final long flightUid;
        public final int durationSinceArmingMs;
        public final int durationSinceTakeoffMs;

        public FlightInfo(
            int timeBootMs,
            long flightUid,
            int durationSinceArmingMs,
            int durationSinceTakeoffMs
        ) {
            this.timeBootMs = timeBootMs;
            this.flightUid = flightUid;
            this.durationSinceArmingMs = durationSinceArmingMs;
            this.durationSinceTakeoffMs = durationSinceTakeoffMs;
        }
    }

    public static final class Identification {
        public final String hardwareUid;
        public final long legacyUid;

        public Identification(
            String hardwareUid,
            long legacyUid
        ) {
            this.hardwareUid = hardwareUid;
            this.legacyUid = legacyUid;
        }
    }

    public static final class Product {
        public final int vendorId;
        public final String vendorName;
        public final int productId;
        public final String productName;

        public Product(
            int vendorId,
            String vendorName,
            int productId,
            String productName
        ) {
            this.vendorId = vendorId;
            this.vendorName = vendorName;
            this.productId = productId;
            this.productName = productName;
        }
    }

    public static final class Version {
        public final int flightSwMajor;
        public final int flightSwMinor;
        public final int flightSwPatch;
        public final int flightSwVendorMajor;
        public final int flightSwVendorMinor;
        public final int flightSwVendorPatch;
        public final int osSwMajor;
        public final int osSwMinor;
        public final int osSwPatch;
        public final String flightSwGitHash;
        public final String osSwGitHash;
        public final int flightSwVersionType;

        public Version(
            int flightSwMajor,
            int flightSwMinor,
            int flightSwPatch,
            int flightSwVendorMajor,
            int flightSwVendorMinor,
            int flightSwVendorPatch,
            int osSwMajor,
            int osSwMinor,
            int osSwPatch,
            String flightSwGitHash,
            String osSwGitHash,
            int flightSwVersionType
        ) {
            this.flightSwMajor = flightSwMajor;
            this.flightSwMinor = flightSwMinor;
            this.flightSwPatch = flightSwPatch;
            this.flightSwVendorMajor = flightSwVendorMajor;
            this.flightSwVendorMinor = flightSwVendorMinor;
            this.flightSwVendorPatch = flightSwVendorPatch;
            this.osSwMajor = osSwMajor;
            this.osSwMinor = osSwMinor;
            this.osSwPatch = osSwPatch;
            this.flightSwGitHash = flightSwGitHash;
            this.osSwGitHash = osSwGitHash;
            this.flightSwVersionType = flightSwVersionType;
        }
    }

    @FunctionalInterface
    public interface FlightInformationCallback {
        void invoke(FlightInfo value);
    }

    public static native long create(long systemHandle);

    public static native void destroy(long pluginHandle);

    public static native FlightInfo getFlightInformation(long pluginHandle);

    public static native Identification getIdentification(long pluginHandle);

    public static native Product getProduct(long pluginHandle);

    public static native Version getVersion(long pluginHandle);

    public static native double getSpeedFactor(long pluginHandle);

    public static native long subscribeFlightInformation(long pluginHandle, FlightInformationCallback callback);

    public static native void unsubscribeFlightInformation(long pluginHandle, long subscriptionHandle);

}