// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/mission_raw_server/mission_raw_server.proto)

package io.mavsdk.kotlin.plugins.mission_raw_server

import io.mavsdk.jni.plugins.mission_raw_server.NativeMissionRawServer
import java.util.concurrent.ConcurrentHashMap

private fun MissionRawServer.MissionItem.toNative(): NativeMissionRawServer.MissionItem =
    NativeMissionRawServer.MissionItem(
        seq,
        frame,
        command,
        current,
        autocontinue,
        param1,
        param2,
        param3,
        param4,
        x,
        y,
        z,
        missionType
    )

private fun NativeMissionRawServer.MissionItem.toKotlin(): MissionRawServer.MissionItem =
    MissionRawServer.MissionItem(
        seq,
        frame,
        command,
        current,
        autocontinue,
        param1,
        param2,
        param3,
        param4,
        x,
        y,
        z,
        missionType
    )

private fun MissionRawServer.MissionPlan.toNative(): NativeMissionRawServer.MissionPlan =
    NativeMissionRawServer.MissionPlan(
        missionItems.map { it.toNative() }.toTypedArray()
    )

private fun NativeMissionRawServer.MissionPlan.toKotlin(): MissionRawServer.MissionPlan =
    MissionRawServer.MissionPlan(
        missionItems.map { it.toKotlin() }
    )

private fun MissionRawServer.MissionProgress.toNative(): NativeMissionRawServer.MissionProgress =
    NativeMissionRawServer.MissionProgress(
        current,
        total
    )

private fun NativeMissionRawServer.MissionProgress.toKotlin(): MissionRawServer.MissionProgress =
    MissionRawServer.MissionProgress(
        current,
        total
    )

private class MissionRawServerNativeImpl(
    private val handle: Long
) : MissionRawServerNative {
    private val activeSubscriptions = ConcurrentHashMap<Long, () -> Unit>()

    override fun subscribeIncomingMission(
        callback: (Int, MissionRawServer.MissionPlan) -> Unit
    ): Long {
        val subscriptionHandle = NativeMissionRawServer.subscribeIncomingMission(
            handle,
            NativeMissionRawServer.IncomingMissionCallback {
                    result, value -> callback(result, value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeMissionRawServer.unsubscribeIncomingMission(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeIncomingMission(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun subscribeCurrentItemChanged(
        callback: (MissionRawServer.MissionItem) -> Unit
    ): Long {
        val subscriptionHandle = NativeMissionRawServer.subscribeCurrentItemChanged(
            handle,
            NativeMissionRawServer.CurrentItemChangedCallback {
                    value -> callback(value.toKotlin())
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeMissionRawServer.unsubscribeCurrentItemChanged(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeCurrentItemChanged(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun setCurrentItemComplete() {
        NativeMissionRawServer.setCurrentItemComplete(handle)
    }

    override fun subscribeClearAll(
        callback: (Int) -> Unit
    ): Long {
        val subscriptionHandle = NativeMissionRawServer.subscribeClearAll(
            handle,
            NativeMissionRawServer.ClearAllCallback {
                    value -> callback(value)
            }
        )
        if (subscriptionHandle != 0L) {
            activeSubscriptions[subscriptionHandle] = {
                NativeMissionRawServer.unsubscribeClearAll(handle, subscriptionHandle)
            }
        }
        return subscriptionHandle
    }

    override fun unsubscribeClearAll(subscriptionHandle: Long) {
        activeSubscriptions.remove(subscriptionHandle)?.invoke()
    }

    override fun destroy() {
        activeSubscriptions.keys.toList().forEach { subscriptionHandle ->
            activeSubscriptions.remove(subscriptionHandle)?.invoke()
        }
        NativeMissionRawServer.destroy(handle)
    }
}

internal actual fun createMissionRawServerNative(systemHandle: Long): MissionRawServerNative =
    MissionRawServerNativeImpl(NativeMissionRawServer.create(systemHandle))
