// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/log_streaming/log_streaming.proto)

package io.mavsdk.kotlin.plugins.log_streaming

import io.mavsdk.kotlin.System
import kotlin.coroutines.resume
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.suspendCancellableCoroutine

class LogStreaming internal constructor(private val native: LogStreamingNative) : AutoCloseable {
    private var closed = false

    enum class Result(val value: Int) {
        SUCCESS(0),
        NO_SYSTEM(1),
        CONNECTION_ERROR(2),
        BUSY(3),
        COMMAND_DENIED(4),
        TIMEOUT(5),
        UNSUPPORTED(6),
        UNKNOWN(7);

        companion object {
            fun fromValue(value: Int): Result = entries.find { it.value == value } ?: UNKNOWN
        }
    }

    data class LogStreamingRaw(val dataBase64: String)

    suspend fun startLogStreaming(): Result = suspendCancellableCoroutine { continuation ->
        val callbackGuard = LogStreamingCallbackGuard()
        native.startLogStreamingAsync() { result ->
            val parsedResult = Result.fromValue(result)
            if (continuation.isActive && true && callbackGuard.tryClaim()) {
                continuation.resume(parsedResult)
            }
        }
    }

    suspend fun stopLogStreaming(): Result = suspendCancellableCoroutine { continuation ->
        val callbackGuard = LogStreamingCallbackGuard()
        native.stopLogStreamingAsync() { result ->
            val parsedResult = Result.fromValue(result)
            if (continuation.isActive && true && callbackGuard.tryClaim()) {
                continuation.resume(parsedResult)
            }
        }
    }

    fun subscribeLogStreamingRaw(): Flow<LogStreamingRaw> = callbackFlow {
        val subscriptionHandle = native.subscribeLogStreamingRaw() { value -> trySend(value) }
        awaitClose { native.unsubscribeLogStreamingRaw(subscriptionHandle) }
    }

    override fun close() {
        if (closed) return
        closed = true
        native.destroy()
    }

    class LogStreamingException(val result: Result, message: String) : Exception(message)

    companion object {
        fun create(system: System): LogStreaming =
            LogStreaming(createLogStreamingNative(system.getHandle())).also {
                system.registerPlugin(it)
            }
    }
}

internal interface LogStreamingNative {
    fun startLogStreamingAsync(callback: (Int) -> Unit)

    fun stopLogStreamingAsync(callback: (Int) -> Unit)

    fun subscribeLogStreamingRaw(callback: (LogStreaming.LogStreamingRaw) -> Unit): Long

    fun unsubscribeLogStreamingRaw(subscriptionHandle: Long)

    fun destroy()
}

internal expect fun createLogStreamingNative(systemHandle: Long): LogStreamingNative

internal expect class LogStreamingCallbackGuard() {
    fun tryClaim(): Boolean
}
