// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/action/action.proto)

#include <jni.h>
#include "cmavsdk/plugins/action/action.h"
#include "../../jni_utils.h"

#include <utility>
#include <vector>

using namespace mavsdk::jni;





// ===== Arm Callback Wrapper =====
struct ArmCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ArmCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== ArmForce Callback Wrapper =====
struct ArmForceCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ArmForceCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Disarm Callback Wrapper =====
struct DisarmCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DisarmCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Takeoff Callback Wrapper =====
struct TakeoffCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    TakeoffCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Land Callback Wrapper =====
struct LandCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    LandCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Reboot Callback Wrapper =====
struct RebootCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    RebootCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Shutdown Callback Wrapper =====
struct ShutdownCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ShutdownCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Terminate Callback Wrapper =====
struct TerminateCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    TerminateCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Kill Callback Wrapper =====
struct KillCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    KillCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== ReturnToLaunch Callback Wrapper =====
struct ReturnToLaunchCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ReturnToLaunchCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== GotoLocation Callback Wrapper =====
struct GotoLocationCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    GotoLocationCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== DoOrbit Callback Wrapper =====
struct DoOrbitCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DoOrbitCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== Hold Callback Wrapper =====
struct HoldCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    HoldCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetActuator Callback Wrapper =====
struct SetActuatorCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetActuatorCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetRelay Callback Wrapper =====
struct SetRelayCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetRelayCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== TransitionToFixedwing Callback Wrapper =====
struct TransitionToFixedwingCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    TransitionToFixedwingCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== TransitionToMulticopter Callback Wrapper =====
struct TransitionToMulticopterCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    TransitionToMulticopterCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== GetTakeoffAltitude Callback Wrapper =====
struct GetTakeoffAltitudeCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    GetTakeoffAltitudeCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(IF)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result, const float altitude) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result),
            static_cast<jfloat>(altitude));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetTakeoffAltitude Callback Wrapper =====
struct SetTakeoffAltitudeCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetTakeoffAltitudeCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== GetReturnToLaunchAltitude Callback Wrapper =====
struct GetReturnToLaunchAltitudeCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    GetReturnToLaunchAltitudeCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(IF)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result, const float relative_altitude_m) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result),
            static_cast<jfloat>(relative_altitude_m));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetReturnToLaunchAltitude Callback Wrapper =====
struct SetReturnToLaunchAltitudeCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetReturnToLaunchAltitudeCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetCurrentSpeed Callback Wrapper =====
struct SetCurrentSpeedCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetCurrentSpeedCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_action_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

extern "C" {

// ===== Action.Companion.createNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_00024Companion_createNative(
    JNIEnv* env,
    jclass clazz,
    jlong systemHandle) {

    if (!systemHandle) {
        throwMavsdkError(env, "OperationError", "Invalid system handle");
        return 0;
    }

    mavsdk_action_t handle = mavsdk_action_create(
        reinterpret_cast<mavsdk_system_t>(systemHandle)
    );

    if (!handle) {
        throwMavsdkError(env, "OperationError", "Failed to create Action plugin");
        return 0;
    }

    return reinterpret_cast<jlong>(handle);
}

// ===== Action.destroy =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_destroy(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return;

    mavsdk_action_destroy(reinterpret_cast<mavsdk_action_t>(handle));
}


// ===== Action.armBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_armBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_arm(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.armAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_armAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new ArmCallbackWrapper(env, callback);

    mavsdk_action_arm_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<ArmCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.arm_forceBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_armForceBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_arm_force(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.arm_forceAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_armForceAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new ArmForceCallbackWrapper(env, callback);

    mavsdk_action_arm_force_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<ArmForceCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.disarmBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_disarmBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_disarm(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.disarmAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_disarmAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new DisarmCallbackWrapper(env, callback);

    mavsdk_action_disarm_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<DisarmCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.takeoffBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_takeoffBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_takeoff(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.takeoffAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_takeoffAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new TakeoffCallbackWrapper(env, callback);

    mavsdk_action_takeoff_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<TakeoffCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.landBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_landBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_land(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.landAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_landAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new LandCallbackWrapper(env, callback);

    mavsdk_action_land_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<LandCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.rebootBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_rebootBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_reboot(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.rebootAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_rebootAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new RebootCallbackWrapper(env, callback);

    mavsdk_action_reboot_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<RebootCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.shutdownBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_shutdownBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_shutdown(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.shutdownAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_shutdownAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new ShutdownCallbackWrapper(env, callback);

    mavsdk_action_shutdown_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<ShutdownCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.terminateBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_terminateBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_terminate(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.terminateAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_terminateAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new TerminateCallbackWrapper(env, callback);

    mavsdk_action_terminate_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<TerminateCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.killBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_killBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_kill(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.killAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_killAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new KillCallbackWrapper(env, callback);

    mavsdk_action_kill_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<KillCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.return_to_launchBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_returnToLaunchBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_return_to_launch(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.return_to_launchAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_returnToLaunchAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new ReturnToLaunchCallbackWrapper(env, callback);

    mavsdk_action_return_to_launch_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<ReturnToLaunchCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.goto_locationBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_gotoLocationBlocking(
    JNIEnv* env,
    jobject obj,
    jdouble latitude_deg,
    jdouble longitude_deg,
    jfloat absolute_altitude_m,
    jfloat yaw_deg) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_goto_location(
        reinterpret_cast<mavsdk_action_t>(handle),
        latitude_deg,
        longitude_deg,
        absolute_altitude_m,
        yaw_deg    );

    return static_cast<jint>(result);
}

// ===== Action.goto_locationAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_gotoLocationAsyncNative(
    JNIEnv* env,
    jobject obj,
    jdouble latitude_deg,
    jdouble longitude_deg,
    jfloat absolute_altitude_m,
    jfloat yaw_deg,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new GotoLocationCallbackWrapper(env, callback);

    mavsdk_action_goto_location_async(
        reinterpret_cast<mavsdk_action_t>(handle),        latitude_deg,        longitude_deg,        absolute_altitude_m,        yaw_deg,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<GotoLocationCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.do_orbitBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_doOrbitBlocking(
    JNIEnv* env,
    jobject obj,
    jfloat radius_m,
    jfloat velocity_ms,
    jint yaw_behavior,
    jdouble latitude_deg,
    jdouble longitude_deg,
    jdouble absolute_altitude_m) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_do_orbit(
        reinterpret_cast<mavsdk_action_t>(handle),
        radius_m,
        velocity_ms,
        static_cast<mavsdk_action_orbit_yaw_behavior_t>(yaw_behavior),
        latitude_deg,
        longitude_deg,
        absolute_altitude_m    );

    return static_cast<jint>(result);
}

// ===== Action.do_orbitAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_doOrbitAsyncNative(
    JNIEnv* env,
    jobject obj,
    jfloat radius_m,
    jfloat velocity_ms,
    jint yaw_behavior,
    jdouble latitude_deg,
    jdouble longitude_deg,
    jdouble absolute_altitude_m,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new DoOrbitCallbackWrapper(env, callback);

    mavsdk_action_do_orbit_async(
        reinterpret_cast<mavsdk_action_t>(handle),        radius_m,        velocity_ms,        static_cast<mavsdk_action_orbit_yaw_behavior_t>(yaw_behavior),        latitude_deg,        longitude_deg,        absolute_altitude_m,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<DoOrbitCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.holdBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_holdBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_hold(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.holdAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_holdAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new HoldCallbackWrapper(env, callback);

    mavsdk_action_hold_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<HoldCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_actuatorBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setActuatorBlocking(
    JNIEnv* env,
    jobject obj,
    jint index,
    jfloat value) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_actuator(
        reinterpret_cast<mavsdk_action_t>(handle),
        index,
        value    );

    return static_cast<jint>(result);
}

// ===== Action.set_actuatorAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setActuatorAsyncNative(
    JNIEnv* env,
    jobject obj,
    jint index,
    jfloat value,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new SetActuatorCallbackWrapper(env, callback);

    mavsdk_action_set_actuator_async(
        reinterpret_cast<mavsdk_action_t>(handle),        index,        value,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<SetActuatorCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_relayBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setRelayBlocking(
    JNIEnv* env,
    jobject obj,
    jint index,
    jint setting) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_relay(
        reinterpret_cast<mavsdk_action_t>(handle),
        index,
        static_cast<mavsdk_action_relay_command_t>(setting)    );

    return static_cast<jint>(result);
}

// ===== Action.set_relayAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setRelayAsyncNative(
    JNIEnv* env,
    jobject obj,
    jint index,
    jint setting,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new SetRelayCallbackWrapper(env, callback);

    mavsdk_action_set_relay_async(
        reinterpret_cast<mavsdk_action_t>(handle),        index,        static_cast<mavsdk_action_relay_command_t>(setting),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<SetRelayCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.transition_to_fixedwingBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_transitionToFixedwingBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_transition_to_fixedwing(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.transition_to_fixedwingAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_transitionToFixedwingAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new TransitionToFixedwingCallbackWrapper(env, callback);

    mavsdk_action_transition_to_fixedwing_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<TransitionToFixedwingCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.transition_to_multicopterBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_transitionToMulticopterBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_transition_to_multicopter(
        reinterpret_cast<mavsdk_action_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== Action.transition_to_multicopterAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_transitionToMulticopterAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new TransitionToMulticopterCallbackWrapper(env, callback);

    mavsdk_action_transition_to_multicopter_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<TransitionToMulticopterCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.get_takeoff_altitudeBlocking =====
JNIEXPORT jfloat JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_getTakeoffAltitudeBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return {};


    float ret_val{};
    mavsdk_action_result_t result = mavsdk_action_get_takeoff_altitude(
        reinterpret_cast<mavsdk_action_t>(handle),
        &ret_val
    );

    if (result != MAVSDK_ACTION_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "get_takeoff_altitude failed");
        return {};
    }

    return static_cast<jfloat>(ret_val);
}

// ===== Action.get_takeoff_altitudeAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_getTakeoffAltitudeAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new GetTakeoffAltitudeCallbackWrapper(env, callback);

    mavsdk_action_get_takeoff_altitude_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, const float value, void* user_data) {
            auto* w = static_cast<GetTakeoffAltitudeCallbackWrapper*>(user_data);
            (*w)(result, value);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_takeoff_altitudeBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setTakeoffAltitudeBlocking(
    JNIEnv* env,
    jobject obj,
    jfloat altitude) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_takeoff_altitude(
        reinterpret_cast<mavsdk_action_t>(handle),
        altitude    );

    return static_cast<jint>(result);
}

// ===== Action.set_takeoff_altitudeAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setTakeoffAltitudeAsyncNative(
    JNIEnv* env,
    jobject obj,
    jfloat altitude,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new SetTakeoffAltitudeCallbackWrapper(env, callback);

    mavsdk_action_set_takeoff_altitude_async(
        reinterpret_cast<mavsdk_action_t>(handle),        altitude,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<SetTakeoffAltitudeCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.get_return_to_launch_altitudeBlocking =====
JNIEXPORT jfloat JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_getReturnToLaunchAltitudeBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return {};


    float ret_val{};
    mavsdk_action_result_t result = mavsdk_action_get_return_to_launch_altitude(
        reinterpret_cast<mavsdk_action_t>(handle),
        &ret_val
    );

    if (result != MAVSDK_ACTION_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "get_return_to_launch_altitude failed");
        return {};
    }

    return static_cast<jfloat>(ret_val);
}

// ===== Action.get_return_to_launch_altitudeAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_getReturnToLaunchAltitudeAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new GetReturnToLaunchAltitudeCallbackWrapper(env, callback);

    mavsdk_action_get_return_to_launch_altitude_async(
        reinterpret_cast<mavsdk_action_t>(handle),        [](const mavsdk_action_result_t result, const float value, void* user_data) {
            auto* w = static_cast<GetReturnToLaunchAltitudeCallbackWrapper*>(user_data);
            (*w)(result, value);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_return_to_launch_altitudeBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setReturnToLaunchAltitudeBlocking(
    JNIEnv* env,
    jobject obj,
    jfloat relative_altitude_m) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_return_to_launch_altitude(
        reinterpret_cast<mavsdk_action_t>(handle),
        relative_altitude_m    );

    return static_cast<jint>(result);
}

// ===== Action.set_return_to_launch_altitudeAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setReturnToLaunchAltitudeAsyncNative(
    JNIEnv* env,
    jobject obj,
    jfloat relative_altitude_m,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new SetReturnToLaunchAltitudeCallbackWrapper(env, callback);

    mavsdk_action_set_return_to_launch_altitude_async(
        reinterpret_cast<mavsdk_action_t>(handle),        relative_altitude_m,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<SetReturnToLaunchAltitudeCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_current_speedBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setCurrentSpeedBlocking(
    JNIEnv* env,
    jobject obj,
    jfloat speed_m_s) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_current_speed(
        reinterpret_cast<mavsdk_action_t>(handle),
        speed_m_s    );

    return static_cast<jint>(result);
}

// ===== Action.set_current_speedAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setCurrentSpeedAsyncNative(
    JNIEnv* env,
    jobject obj,
    jfloat speed_m_s,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle || !callback) return;


    auto* wrapper = new SetCurrentSpeedCallbackWrapper(env, callback);

    mavsdk_action_set_current_speed_async(
        reinterpret_cast<mavsdk_action_t>(handle),        speed_m_s,        [](const mavsdk_action_result_t result, void* user_data) {
            auto* w = static_cast<SetCurrentSpeedCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== Action.set_gps_global_originBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_action_Action_setGpsGlobalOriginBlocking(
    JNIEnv* env,
    jobject obj,
    jdouble latitude_deg,
    jdouble longitude_deg,
    jfloat absolute_altitude_m) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/action/Action");
    if (!handle) return MAVSDK_ACTION_RESULT_UNKNOWN;


    mavsdk_action_result_t result = mavsdk_action_set_gps_global_origin(
        reinterpret_cast<mavsdk_action_t>(handle),
        latitude_deg,
        longitude_deg,
        absolute_altitude_m    );

    return static_cast<jint>(result);
}


} // extern "C"