// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/mission_raw/mission_raw.proto)

#include <jni.h>
#include "cmavsdk/plugins/mission_raw/mission_raw.h"
#include "../../jni_utils.h"

#include <utility>
#include <vector>

using namespace mavsdk::jni;





// ===== UploadMission Callback Wrapper =====
struct UploadMissionCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    UploadMissionCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== UploadGeofence Callback Wrapper =====
struct UploadGeofenceCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    UploadGeofenceCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== UploadRallyPoints Callback Wrapper =====
struct UploadRallyPointsCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    UploadRallyPointsCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== DownloadMission Callback Wrapper =====
struct DownloadMissionCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DownloadMissionCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(ILjava/lang/Object;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== DownloadGeofence Callback Wrapper =====
struct DownloadGeofenceCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DownloadGeofenceCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(ILjava/lang/Object;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== DownloadRallypoints Callback Wrapper =====
struct DownloadRallypointsCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    DownloadRallypointsCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(ILjava/lang/Object;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== StartMission Callback Wrapper =====
struct StartMissionCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    StartMissionCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== PauseMission Callback Wrapper =====
struct PauseMissionCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    PauseMissionCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== ClearMission Callback Wrapper =====
struct ClearMissionCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    ClearMissionCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== SetCurrentMissionItem Callback Wrapper =====
struct SetCurrentMissionItemCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    SetCurrentMissionItemCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== MissionProgress Callback Wrapper =====
struct MissionProgressCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    MissionProgressCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(Lio/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionProgress;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_mission_raw_mission_progress_t value) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionProgress");
        if (!retClass) { return; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(II)V");
        jobject retObj = env->NewObject(retClass, retCtor            , static_cast<jint>(value.current)            , static_cast<jint>(value.total)        );
        env->DeleteLocalRef(retClass);
        env->CallVoidMethod(callback.get(), invokeMethod, retObj);
        env->DeleteLocalRef(retObj);

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== MissionChanged Callback Wrapper =====
struct MissionChangedCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    MissionChangedCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(Z)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const bool value) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jboolean>(value));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

extern "C" {

// ===== MissionRaw.Companion.createNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_00024Companion_createNative(
    JNIEnv* env,
    jclass clazz,
    jlong systemHandle) {

    if (!systemHandle) {
        throwMavsdkError(env, "OperationError", "Invalid system handle");
        return 0;
    }

    mavsdk_mission_raw_t handle = mavsdk_mission_raw_create(
        reinterpret_cast<mavsdk_system_t>(systemHandle)
    );

    if (!handle) {
        throwMavsdkError(env, "OperationError", "Failed to create MissionRaw plugin");
        return 0;
    }

    return reinterpret_cast<jlong>(handle);
}

// ===== MissionRaw.destroy =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_destroy(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return;

    mavsdk_mission_raw_destroy(reinterpret_cast<mavsdk_mission_raw_t>(handle));
}


// ===== MissionRaw.upload_missionBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadMissionBlocking(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_upload_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, 0 /* TODO: repeated param */    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.upload_missionAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadMissionAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new UploadMissionCallbackWrapper(env, callback);

    mavsdk_mission_raw_upload_mission_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        nullptr, 0, /* TODO: repeated param */        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<UploadMissionCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.upload_geofenceBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadGeofenceBlocking(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_upload_geofence(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, 0 /* TODO: repeated param */    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.upload_geofenceAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadGeofenceAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new UploadGeofenceCallbackWrapper(env, callback);

    mavsdk_mission_raw_upload_geofence_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        nullptr, 0, /* TODO: repeated param */        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<UploadGeofenceCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.upload_rally_pointsBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadRallyPointsBlocking(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_upload_rally_points(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, 0 /* TODO: repeated param */    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.upload_rally_pointsAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_uploadRallyPointsAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject mission_items /* TODO: repeated param */,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new UploadRallyPointsCallbackWrapper(env, callback);

    mavsdk_mission_raw_upload_rally_points_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        nullptr, 0, /* TODO: repeated param */        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<UploadRallyPointsCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.cancel_mission_uploadBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_cancelMissionUploadBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_cancel_mission_upload(
        reinterpret_cast<mavsdk_mission_raw_t>(handle)    );

    return static_cast<jint>(result);
}


// ===== MissionRaw.download_missionBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadMissionBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};


    mavsdk_mission_raw_download_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, nullptr
    );
    return nullptr;
}

// ===== MissionRaw.download_missionAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadMissionAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new DownloadMissionCallbackWrapper(env, callback);

    mavsdk_mission_raw_download_mission_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, const mavsdk_mission_raw_mission_item_t* items, size_t count, void* user_data) {
            auto* w = static_cast<DownloadMissionCallbackWrapper*>(user_data);
            (*w)(result); /* TODO: pass items/count to Java */
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.download_geofenceBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadGeofenceBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};


    mavsdk_mission_raw_download_geofence(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, nullptr
    );
    return nullptr;
}

// ===== MissionRaw.download_geofenceAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadGeofenceAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new DownloadGeofenceCallbackWrapper(env, callback);

    mavsdk_mission_raw_download_geofence_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, const mavsdk_mission_raw_mission_item_t* items, size_t count, void* user_data) {
            auto* w = static_cast<DownloadGeofenceCallbackWrapper*>(user_data);
            (*w)(result); /* TODO: pass items/count to Java */
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.download_rallypointsBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadRallypointsBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};


    mavsdk_mission_raw_download_rallypoints(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        nullptr, nullptr
    );
    return nullptr;
}

// ===== MissionRaw.download_rallypointsAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_downloadRallypointsAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new DownloadRallypointsCallbackWrapper(env, callback);

    mavsdk_mission_raw_download_rallypoints_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, const mavsdk_mission_raw_mission_item_t* items, size_t count, void* user_data) {
            auto* w = static_cast<DownloadRallypointsCallbackWrapper*>(user_data);
            (*w)(result); /* TODO: pass items/count to Java */
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.cancel_mission_downloadBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_cancelMissionDownloadBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_cancel_mission_download(
        reinterpret_cast<mavsdk_mission_raw_t>(handle)    );

    return static_cast<jint>(result);
}


// ===== MissionRaw.start_missionBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_startMissionBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_start_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.start_missionAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_startMissionAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new StartMissionCallbackWrapper(env, callback);

    mavsdk_mission_raw_start_mission_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<StartMissionCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.pause_missionBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_pauseMissionBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_pause_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.pause_missionAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_pauseMissionAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new PauseMissionCallbackWrapper(env, callback);

    mavsdk_mission_raw_pause_mission_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<PauseMissionCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.clear_missionBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_clearMissionBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_clear_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.clear_missionAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_clearMissionAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new ClearMissionCallbackWrapper(env, callback);

    mavsdk_mission_raw_clear_mission_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<ClearMissionCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.set_current_mission_itemBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_setCurrentMissionItemBlocking(
    JNIEnv* env,
    jobject obj,
    jint index) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return MAVSDK_MISSION_RAW_RESULT_UNKNOWN;


    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_set_current_mission_item(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        index    );

    return static_cast<jint>(result);
}

// ===== MissionRaw.set_current_mission_itemAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_setCurrentMissionItemAsyncNative(
    JNIEnv* env,
    jobject obj,
    jint index,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return;


    auto* wrapper = new SetCurrentMissionItemCallbackWrapper(env, callback);

    mavsdk_mission_raw_set_current_mission_item_async(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),        index,        [](const mavsdk_mission_raw_result_t result, void* user_data) {
            auto* w = static_cast<SetCurrentMissionItemCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== MissionRaw.mission_progressBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_missionProgressBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};


    mavsdk_mission_raw_mission_progress_t ret_val{};
    mavsdk_mission_raw_mission_progress(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        &ret_val
    );

        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionProgress");
        if (!retClass) { return nullptr; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(II)V");
        jobject retObj = env->NewObject(retClass, retCtor            , static_cast<jint>(ret_val.current)            , static_cast<jint>(ret_val.total)        );
        env->DeleteLocalRef(retClass);
    mavsdk_mission_raw_mission_progress_destroy(&ret_val);
    return retObj;
}

// ===== MissionRaw.subscribeMissionProgressNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_subscribeMissionProgressNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return 0;


    auto* wrapper = new MissionProgressCallbackWrapper(env, callback);

    mavsdk_mission_raw_mission_progress_handle_t subscription_handle =
        mavsdk_mission_raw_subscribe_mission_progress(
            reinterpret_cast<mavsdk_mission_raw_t>(handle),            [](const mavsdk_mission_raw_mission_progress_t value, void* user_data) {
                auto* w = static_cast<MissionProgressCallbackWrapper*>(user_data);
                (*w)(value);
            },
            wrapper
        );

    auto* handle_pair = new std::pair<
        mavsdk_mission_raw_mission_progress_handle_t,
        MissionProgressCallbackWrapper*>(
        subscription_handle, wrapper
    );

    return reinterpret_cast<jlong>(handle_pair);
}

// ===== MissionRaw.unsubscribeMissionProgress =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_unsubscribeMissionProgress(
    JNIEnv* env,
    jobject obj,
    jlong subscriptionHandle) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !subscriptionHandle) return;

    auto* handle_pair = reinterpret_cast<
        std::pair<mavsdk_mission_raw_mission_progress_handle_t,
                  MissionProgressCallbackWrapper*>*>(subscriptionHandle);

    if (handle_pair) {
        mavsdk_mission_raw_unsubscribe_mission_progress(
            reinterpret_cast<mavsdk_mission_raw_t>(handle),
            handle_pair->first
        );
        delete handle_pair->second;
        delete handle_pair;
    }
}


// ===== MissionRaw.subscribeMissionChangedNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_subscribeMissionChangedNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !callback) return 0;


    auto* wrapper = new MissionChangedCallbackWrapper(env, callback);

    mavsdk_mission_raw_mission_changed_handle_t subscription_handle =
        mavsdk_mission_raw_subscribe_mission_changed(
            reinterpret_cast<mavsdk_mission_raw_t>(handle),            [](const bool value, void* user_data) {
                auto* w = static_cast<MissionChangedCallbackWrapper*>(user_data);
                (*w)(value);
            },
            wrapper
        );

    auto* handle_pair = new std::pair<
        mavsdk_mission_raw_mission_changed_handle_t,
        MissionChangedCallbackWrapper*>(
        subscription_handle, wrapper
    );

    return reinterpret_cast<jlong>(handle_pair);
}

// ===== MissionRaw.unsubscribeMissionChanged =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_unsubscribeMissionChanged(
    JNIEnv* env,
    jobject obj,
    jlong subscriptionHandle) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle || !subscriptionHandle) return;

    auto* handle_pair = reinterpret_cast<
        std::pair<mavsdk_mission_raw_mission_changed_handle_t,
                  MissionChangedCallbackWrapper*>*>(subscriptionHandle);

    if (handle_pair) {
        mavsdk_mission_raw_unsubscribe_mission_changed(
            reinterpret_cast<mavsdk_mission_raw_t>(handle),
            handle_pair->first
        );
        delete handle_pair->second;
        delete handle_pair;
    }
}


// ===== MissionRaw.import_qgroundcontrol_missionBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_importQgroundcontrolMissionBlocking(
    JNIEnv* env,
    jobject obj,
    jstring qgc_plan_path) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};

    JStringHolder qgc_plan_path_holder(env, qgc_plan_path);

    mavsdk_mission_raw_mission_import_data_t ret_val{};
    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_import_qgroundcontrol_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        const_cast<char*>(qgc_plan_path_holder.c_str()),
        &ret_val
    );

    if (result != MAVSDK_MISSION_RAW_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "import_qgroundcontrol_mission failed");
        return nullptr;
    }

        jclass arrayListClass_MissionImportData = env->FindClass("java/util/ArrayList");
        jmethodID arrayListCtor_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "<init>", "()V");
        jmethodID arrayListAdd_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "add", "(Ljava/lang/Object;)Z");        jobject list_mission_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_mission_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_mission_items = env->GetMethodID(elemClass_mission_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.mission_items_size; i++) {
                jobject elem = env->NewObject(elemClass_mission_items, elemCtor_mission_items                    , static_cast<jint>(ret_val.mission_items[i].seq)                    , static_cast<jint>(ret_val.mission_items[i].frame)                    , static_cast<jint>(ret_val.mission_items[i].command)                    , static_cast<jint>(ret_val.mission_items[i].current)                    , static_cast<jint>(ret_val.mission_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.mission_items[i].param1)                    , static_cast<jfloat>(ret_val.mission_items[i].param2)                    , static_cast<jfloat>(ret_val.mission_items[i].param3)                    , static_cast<jfloat>(ret_val.mission_items[i].param4)                    , static_cast<jint>(ret_val.mission_items[i].x)                    , static_cast<jint>(ret_val.mission_items[i].y)                    , static_cast<jfloat>(ret_val.mission_items[i].z)                    , static_cast<jint>(ret_val.mission_items[i].mission_type)                );
                env->CallBooleanMethod(list_mission_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_mission_items);
        }        jobject list_geofence_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_geofence_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_geofence_items = env->GetMethodID(elemClass_geofence_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.geofence_items_size; i++) {
                jobject elem = env->NewObject(elemClass_geofence_items, elemCtor_geofence_items                    , static_cast<jint>(ret_val.geofence_items[i].seq)                    , static_cast<jint>(ret_val.geofence_items[i].frame)                    , static_cast<jint>(ret_val.geofence_items[i].command)                    , static_cast<jint>(ret_val.geofence_items[i].current)                    , static_cast<jint>(ret_val.geofence_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.geofence_items[i].param1)                    , static_cast<jfloat>(ret_val.geofence_items[i].param2)                    , static_cast<jfloat>(ret_val.geofence_items[i].param3)                    , static_cast<jfloat>(ret_val.geofence_items[i].param4)                    , static_cast<jint>(ret_val.geofence_items[i].x)                    , static_cast<jint>(ret_val.geofence_items[i].y)                    , static_cast<jfloat>(ret_val.geofence_items[i].z)                    , static_cast<jint>(ret_val.geofence_items[i].mission_type)                );
                env->CallBooleanMethod(list_geofence_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_geofence_items);
        }        jobject list_rally_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_rally_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_rally_items = env->GetMethodID(elemClass_rally_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.rally_items_size; i++) {
                jobject elem = env->NewObject(elemClass_rally_items, elemCtor_rally_items                    , static_cast<jint>(ret_val.rally_items[i].seq)                    , static_cast<jint>(ret_val.rally_items[i].frame)                    , static_cast<jint>(ret_val.rally_items[i].command)                    , static_cast<jint>(ret_val.rally_items[i].current)                    , static_cast<jint>(ret_val.rally_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.rally_items[i].param1)                    , static_cast<jfloat>(ret_val.rally_items[i].param2)                    , static_cast<jfloat>(ret_val.rally_items[i].param3)                    , static_cast<jfloat>(ret_val.rally_items[i].param4)                    , static_cast<jint>(ret_val.rally_items[i].x)                    , static_cast<jint>(ret_val.rally_items[i].y)                    , static_cast<jfloat>(ret_val.rally_items[i].z)                    , static_cast<jint>(ret_val.rally_items[i].mission_type)                );
                env->CallBooleanMethod(list_rally_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_rally_items);
        }env->DeleteLocalRef(arrayListClass_MissionImportData);        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionImportData");
        if (!retClass) { return nullptr; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V");
        jobject retObj = env->NewObject(retClass, retCtor            , list_mission_items            , list_geofence_items            , list_rally_items        );
        env->DeleteLocalRef(retClass);        env->DeleteLocalRef(list_mission_items);        env->DeleteLocalRef(list_geofence_items);        env->DeleteLocalRef(list_rally_items);
    mavsdk_mission_raw_mission_import_data_destroy(&ret_val);
    return retObj;
}


// ===== MissionRaw.import_qgroundcontrol_mission_from_stringBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_importQgroundcontrolMissionFromStringBlocking(
    JNIEnv* env,
    jobject obj,
    jstring qgc_plan) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};

    JStringHolder qgc_plan_holder(env, qgc_plan);

    mavsdk_mission_raw_mission_import_data_t ret_val{};
    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_import_qgroundcontrol_mission_from_string(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        const_cast<char*>(qgc_plan_holder.c_str()),
        &ret_val
    );

    if (result != MAVSDK_MISSION_RAW_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "import_qgroundcontrol_mission_from_string failed");
        return nullptr;
    }

        jclass arrayListClass_MissionImportData = env->FindClass("java/util/ArrayList");
        jmethodID arrayListCtor_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "<init>", "()V");
        jmethodID arrayListAdd_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "add", "(Ljava/lang/Object;)Z");        jobject list_mission_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_mission_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_mission_items = env->GetMethodID(elemClass_mission_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.mission_items_size; i++) {
                jobject elem = env->NewObject(elemClass_mission_items, elemCtor_mission_items                    , static_cast<jint>(ret_val.mission_items[i].seq)                    , static_cast<jint>(ret_val.mission_items[i].frame)                    , static_cast<jint>(ret_val.mission_items[i].command)                    , static_cast<jint>(ret_val.mission_items[i].current)                    , static_cast<jint>(ret_val.mission_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.mission_items[i].param1)                    , static_cast<jfloat>(ret_val.mission_items[i].param2)                    , static_cast<jfloat>(ret_val.mission_items[i].param3)                    , static_cast<jfloat>(ret_val.mission_items[i].param4)                    , static_cast<jint>(ret_val.mission_items[i].x)                    , static_cast<jint>(ret_val.mission_items[i].y)                    , static_cast<jfloat>(ret_val.mission_items[i].z)                    , static_cast<jint>(ret_val.mission_items[i].mission_type)                );
                env->CallBooleanMethod(list_mission_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_mission_items);
        }        jobject list_geofence_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_geofence_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_geofence_items = env->GetMethodID(elemClass_geofence_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.geofence_items_size; i++) {
                jobject elem = env->NewObject(elemClass_geofence_items, elemCtor_geofence_items                    , static_cast<jint>(ret_val.geofence_items[i].seq)                    , static_cast<jint>(ret_val.geofence_items[i].frame)                    , static_cast<jint>(ret_val.geofence_items[i].command)                    , static_cast<jint>(ret_val.geofence_items[i].current)                    , static_cast<jint>(ret_val.geofence_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.geofence_items[i].param1)                    , static_cast<jfloat>(ret_val.geofence_items[i].param2)                    , static_cast<jfloat>(ret_val.geofence_items[i].param3)                    , static_cast<jfloat>(ret_val.geofence_items[i].param4)                    , static_cast<jint>(ret_val.geofence_items[i].x)                    , static_cast<jint>(ret_val.geofence_items[i].y)                    , static_cast<jfloat>(ret_val.geofence_items[i].z)                    , static_cast<jint>(ret_val.geofence_items[i].mission_type)                );
                env->CallBooleanMethod(list_geofence_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_geofence_items);
        }        jobject list_rally_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_rally_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_rally_items = env->GetMethodID(elemClass_rally_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.rally_items_size; i++) {
                jobject elem = env->NewObject(elemClass_rally_items, elemCtor_rally_items                    , static_cast<jint>(ret_val.rally_items[i].seq)                    , static_cast<jint>(ret_val.rally_items[i].frame)                    , static_cast<jint>(ret_val.rally_items[i].command)                    , static_cast<jint>(ret_val.rally_items[i].current)                    , static_cast<jint>(ret_val.rally_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.rally_items[i].param1)                    , static_cast<jfloat>(ret_val.rally_items[i].param2)                    , static_cast<jfloat>(ret_val.rally_items[i].param3)                    , static_cast<jfloat>(ret_val.rally_items[i].param4)                    , static_cast<jint>(ret_val.rally_items[i].x)                    , static_cast<jint>(ret_val.rally_items[i].y)                    , static_cast<jfloat>(ret_val.rally_items[i].z)                    , static_cast<jint>(ret_val.rally_items[i].mission_type)                );
                env->CallBooleanMethod(list_rally_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_rally_items);
        }env->DeleteLocalRef(arrayListClass_MissionImportData);        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionImportData");
        if (!retClass) { return nullptr; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V");
        jobject retObj = env->NewObject(retClass, retCtor            , list_mission_items            , list_geofence_items            , list_rally_items        );
        env->DeleteLocalRef(retClass);        env->DeleteLocalRef(list_mission_items);        env->DeleteLocalRef(list_geofence_items);        env->DeleteLocalRef(list_rally_items);
    mavsdk_mission_raw_mission_import_data_destroy(&ret_val);
    return retObj;
}


// ===== MissionRaw.import_mission_planner_missionBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_importMissionPlannerMissionBlocking(
    JNIEnv* env,
    jobject obj,
    jstring mission_planner_path) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};

    JStringHolder mission_planner_path_holder(env, mission_planner_path);

    mavsdk_mission_raw_mission_import_data_t ret_val{};
    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_import_mission_planner_mission(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        const_cast<char*>(mission_planner_path_holder.c_str()),
        &ret_val
    );

    if (result != MAVSDK_MISSION_RAW_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "import_mission_planner_mission failed");
        return nullptr;
    }

        jclass arrayListClass_MissionImportData = env->FindClass("java/util/ArrayList");
        jmethodID arrayListCtor_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "<init>", "()V");
        jmethodID arrayListAdd_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "add", "(Ljava/lang/Object;)Z");        jobject list_mission_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_mission_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_mission_items = env->GetMethodID(elemClass_mission_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.mission_items_size; i++) {
                jobject elem = env->NewObject(elemClass_mission_items, elemCtor_mission_items                    , static_cast<jint>(ret_val.mission_items[i].seq)                    , static_cast<jint>(ret_val.mission_items[i].frame)                    , static_cast<jint>(ret_val.mission_items[i].command)                    , static_cast<jint>(ret_val.mission_items[i].current)                    , static_cast<jint>(ret_val.mission_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.mission_items[i].param1)                    , static_cast<jfloat>(ret_val.mission_items[i].param2)                    , static_cast<jfloat>(ret_val.mission_items[i].param3)                    , static_cast<jfloat>(ret_val.mission_items[i].param4)                    , static_cast<jint>(ret_val.mission_items[i].x)                    , static_cast<jint>(ret_val.mission_items[i].y)                    , static_cast<jfloat>(ret_val.mission_items[i].z)                    , static_cast<jint>(ret_val.mission_items[i].mission_type)                );
                env->CallBooleanMethod(list_mission_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_mission_items);
        }        jobject list_geofence_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_geofence_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_geofence_items = env->GetMethodID(elemClass_geofence_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.geofence_items_size; i++) {
                jobject elem = env->NewObject(elemClass_geofence_items, elemCtor_geofence_items                    , static_cast<jint>(ret_val.geofence_items[i].seq)                    , static_cast<jint>(ret_val.geofence_items[i].frame)                    , static_cast<jint>(ret_val.geofence_items[i].command)                    , static_cast<jint>(ret_val.geofence_items[i].current)                    , static_cast<jint>(ret_val.geofence_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.geofence_items[i].param1)                    , static_cast<jfloat>(ret_val.geofence_items[i].param2)                    , static_cast<jfloat>(ret_val.geofence_items[i].param3)                    , static_cast<jfloat>(ret_val.geofence_items[i].param4)                    , static_cast<jint>(ret_val.geofence_items[i].x)                    , static_cast<jint>(ret_val.geofence_items[i].y)                    , static_cast<jfloat>(ret_val.geofence_items[i].z)                    , static_cast<jint>(ret_val.geofence_items[i].mission_type)                );
                env->CallBooleanMethod(list_geofence_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_geofence_items);
        }        jobject list_rally_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_rally_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_rally_items = env->GetMethodID(elemClass_rally_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.rally_items_size; i++) {
                jobject elem = env->NewObject(elemClass_rally_items, elemCtor_rally_items                    , static_cast<jint>(ret_val.rally_items[i].seq)                    , static_cast<jint>(ret_val.rally_items[i].frame)                    , static_cast<jint>(ret_val.rally_items[i].command)                    , static_cast<jint>(ret_val.rally_items[i].current)                    , static_cast<jint>(ret_val.rally_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.rally_items[i].param1)                    , static_cast<jfloat>(ret_val.rally_items[i].param2)                    , static_cast<jfloat>(ret_val.rally_items[i].param3)                    , static_cast<jfloat>(ret_val.rally_items[i].param4)                    , static_cast<jint>(ret_val.rally_items[i].x)                    , static_cast<jint>(ret_val.rally_items[i].y)                    , static_cast<jfloat>(ret_val.rally_items[i].z)                    , static_cast<jint>(ret_val.rally_items[i].mission_type)                );
                env->CallBooleanMethod(list_rally_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_rally_items);
        }env->DeleteLocalRef(arrayListClass_MissionImportData);        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionImportData");
        if (!retClass) { return nullptr; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V");
        jobject retObj = env->NewObject(retClass, retCtor            , list_mission_items            , list_geofence_items            , list_rally_items        );
        env->DeleteLocalRef(retClass);        env->DeleteLocalRef(list_mission_items);        env->DeleteLocalRef(list_geofence_items);        env->DeleteLocalRef(list_rally_items);
    mavsdk_mission_raw_mission_import_data_destroy(&ret_val);
    return retObj;
}


// ===== MissionRaw.import_mission_planner_mission_from_stringBlocking =====
JNIEXPORT jobject JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_importMissionPlannerMissionFromStringBlocking(
    JNIEnv* env,
    jobject obj,
    jstring mission_planner_mission) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};

    JStringHolder mission_planner_mission_holder(env, mission_planner_mission);

    mavsdk_mission_raw_mission_import_data_t ret_val{};
    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_import_mission_planner_mission_from_string(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        const_cast<char*>(mission_planner_mission_holder.c_str()),
        &ret_val
    );

    if (result != MAVSDK_MISSION_RAW_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "import_mission_planner_mission_from_string failed");
        return nullptr;
    }

        jclass arrayListClass_MissionImportData = env->FindClass("java/util/ArrayList");
        jmethodID arrayListCtor_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "<init>", "()V");
        jmethodID arrayListAdd_MissionImportData = env->GetMethodID(arrayListClass_MissionImportData, "add", "(Ljava/lang/Object;)Z");        jobject list_mission_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_mission_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_mission_items = env->GetMethodID(elemClass_mission_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.mission_items_size; i++) {
                jobject elem = env->NewObject(elemClass_mission_items, elemCtor_mission_items                    , static_cast<jint>(ret_val.mission_items[i].seq)                    , static_cast<jint>(ret_val.mission_items[i].frame)                    , static_cast<jint>(ret_val.mission_items[i].command)                    , static_cast<jint>(ret_val.mission_items[i].current)                    , static_cast<jint>(ret_val.mission_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.mission_items[i].param1)                    , static_cast<jfloat>(ret_val.mission_items[i].param2)                    , static_cast<jfloat>(ret_val.mission_items[i].param3)                    , static_cast<jfloat>(ret_val.mission_items[i].param4)                    , static_cast<jint>(ret_val.mission_items[i].x)                    , static_cast<jint>(ret_val.mission_items[i].y)                    , static_cast<jfloat>(ret_val.mission_items[i].z)                    , static_cast<jint>(ret_val.mission_items[i].mission_type)                );
                env->CallBooleanMethod(list_mission_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_mission_items);
        }        jobject list_geofence_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_geofence_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_geofence_items = env->GetMethodID(elemClass_geofence_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.geofence_items_size; i++) {
                jobject elem = env->NewObject(elemClass_geofence_items, elemCtor_geofence_items                    , static_cast<jint>(ret_val.geofence_items[i].seq)                    , static_cast<jint>(ret_val.geofence_items[i].frame)                    , static_cast<jint>(ret_val.geofence_items[i].command)                    , static_cast<jint>(ret_val.geofence_items[i].current)                    , static_cast<jint>(ret_val.geofence_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.geofence_items[i].param1)                    , static_cast<jfloat>(ret_val.geofence_items[i].param2)                    , static_cast<jfloat>(ret_val.geofence_items[i].param3)                    , static_cast<jfloat>(ret_val.geofence_items[i].param4)                    , static_cast<jint>(ret_val.geofence_items[i].x)                    , static_cast<jint>(ret_val.geofence_items[i].y)                    , static_cast<jfloat>(ret_val.geofence_items[i].z)                    , static_cast<jint>(ret_val.geofence_items[i].mission_type)                );
                env->CallBooleanMethod(list_geofence_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_geofence_items);
        }        jobject list_rally_items = env->NewObject(arrayListClass_MissionImportData, arrayListCtor_MissionImportData);
        {
            jclass elemClass_rally_items = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionItem");
            jmethodID elemCtor_rally_items = env->GetMethodID(elemClass_rally_items, "<init>", "(IIIIIFFFFIIFI)V");
            for (size_t i = 0; i < ret_val.rally_items_size; i++) {
                jobject elem = env->NewObject(elemClass_rally_items, elemCtor_rally_items                    , static_cast<jint>(ret_val.rally_items[i].seq)                    , static_cast<jint>(ret_val.rally_items[i].frame)                    , static_cast<jint>(ret_val.rally_items[i].command)                    , static_cast<jint>(ret_val.rally_items[i].current)                    , static_cast<jint>(ret_val.rally_items[i].autocontinue)                    , static_cast<jfloat>(ret_val.rally_items[i].param1)                    , static_cast<jfloat>(ret_val.rally_items[i].param2)                    , static_cast<jfloat>(ret_val.rally_items[i].param3)                    , static_cast<jfloat>(ret_val.rally_items[i].param4)                    , static_cast<jint>(ret_val.rally_items[i].x)                    , static_cast<jint>(ret_val.rally_items[i].y)                    , static_cast<jfloat>(ret_val.rally_items[i].z)                    , static_cast<jint>(ret_val.rally_items[i].mission_type)                );
                env->CallBooleanMethod(list_rally_items, arrayListAdd_MissionImportData, elem);
                env->DeleteLocalRef(elem);
            }
            env->DeleteLocalRef(elemClass_rally_items);
        }env->DeleteLocalRef(arrayListClass_MissionImportData);        jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/mission_raw/MissionRaw$MissionImportData");
        if (!retClass) { return nullptr; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V");
        jobject retObj = env->NewObject(retClass, retCtor            , list_mission_items            , list_geofence_items            , list_rally_items        );
        env->DeleteLocalRef(retClass);        env->DeleteLocalRef(list_mission_items);        env->DeleteLocalRef(list_geofence_items);        env->DeleteLocalRef(list_rally_items);
    mavsdk_mission_raw_mission_import_data_destroy(&ret_val);
    return retObj;
}


// ===== MissionRaw.is_mission_finishedBlocking =====
JNIEXPORT jboolean JNICALL
Java_io_mavsdk_kotlin_plugins_mission_1raw_MissionRaw_isMissionFinishedBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/mission_raw/MissionRaw");
    if (!handle) return {};


    bool ret_val{};
    mavsdk_mission_raw_result_t result = mavsdk_mission_raw_is_mission_finished(
        reinterpret_cast<mavsdk_mission_raw_t>(handle),
        &ret_val
    );

    if (result != MAVSDK_MISSION_RAW_RESULT_SUCCESS) {
        throwMavsdkError(env, "OperationError", "is_mission_finished failed");
        return {};
    }

    return static_cast<jboolean>(ret_val);
}


} // extern "C"