// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/log_streaming/log_streaming.proto)

#include <jni.h>
#include "cmavsdk/plugins/log_streaming/log_streaming.h"
#include "../../jni_utils.h"

#include <utility>

using namespace mavsdk::jni;





// ===== StartLogStreaming Callback Wrapper =====
struct StartLogStreamingCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    StartLogStreamingCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_log_streaming_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== StopLogStreaming Callback Wrapper =====
struct StopLogStreamingCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    StopLogStreamingCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(I)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_log_streaming_result_t result) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

        env->CallVoidMethod(callback.get(), invokeMethod, static_cast<jint>(result));

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

// ===== LogStreamingRaw Callback Wrapper =====
struct LogStreamingRawCallbackWrapper {
    GlobalRefHolder callback;
    jmethodID invokeMethod;

    LogStreamingRawCallbackWrapper(JNIEnv* env, jobject callback_obj)
        : callback(env, callback_obj), invokeMethod(nullptr) {

        if (callback.isValid()) {
            jclass callbackClass = env->GetObjectClass(callback_obj);
            invokeMethod = env->GetMethodID(callbackClass, "invoke", "(Lio/mavsdk/kotlin/plugins/log_streaming/LogStreaming$LogStreamingRaw;)V");
            env->DeleteLocalRef(callbackClass);
        }
    }

    void operator()(const mavsdk_log_streaming_log_streaming_raw_t value) const {
        if (!callback.isValid() || !invokeMethod || !g_jvm) {
            return;
        }

        JavaVMAttacher attacher(g_jvm);
        JNIEnv* env = attacher.getEnv();
        if (!env) {
            return;
        }

jclass retClass = env->FindClass("io/mavsdk/kotlin/plugins/log_streaming/LogStreaming$LogStreamingRaw");
        if (!retClass) { return; }
        jmethodID retCtor = env->GetMethodID(retClass, "<init>", "(Ljava/lang/String;)V");
        jobject retObj = env->NewObject(retClass, retCtor            , toJavaString(env, value.data_base64)        );
        env->DeleteLocalRef(retClass);
        env->CallVoidMethod(callback.get(), invokeMethod, retObj);
        env->DeleteLocalRef(retObj);

        if (env->ExceptionCheck()) {
            env->ExceptionDescribe();
            env->ExceptionClear();
        }
    }
};

extern "C" {

// ===== LogStreaming.Companion.createNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_00024Companion_createNative(
    JNIEnv* env,
    jclass clazz,
    jlong systemHandle) {

    if (!systemHandle) {
        throwMavsdkError(env, "OperationError", "Invalid system handle");
        return 0;
    }

    mavsdk_log_streaming_t handle = mavsdk_log_streaming_create(
        reinterpret_cast<mavsdk_system_t>(systemHandle)
    );

    if (!handle) {
        throwMavsdkError(env, "OperationError", "Failed to create LogStreaming plugin");
        return 0;
    }

    return reinterpret_cast<jlong>(handle);
}

// ===== LogStreaming.destroy =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_destroy(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle) return;

    mavsdk_log_streaming_destroy(reinterpret_cast<mavsdk_log_streaming_t>(handle));
}


// ===== LogStreaming.start_log_streamingBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_startLogStreamingBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle) return MAVSDK_LOG_STREAMING_RESULT_UNKNOWN;


    mavsdk_log_streaming_result_t result = mavsdk_log_streaming_start_log_streaming(
        reinterpret_cast<mavsdk_log_streaming_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== LogStreaming.start_log_streamingAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_startLogStreamingAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle || !callback) return;


    auto* wrapper = new StartLogStreamingCallbackWrapper(env, callback);

    mavsdk_log_streaming_start_log_streaming_async(
        reinterpret_cast<mavsdk_log_streaming_t>(handle),        [](const mavsdk_log_streaming_result_t result, void* user_data) {
            auto* w = static_cast<StartLogStreamingCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== LogStreaming.stop_log_streamingBlocking =====
JNIEXPORT jint JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_stopLogStreamingBlocking(
    JNIEnv* env,
    jobject obj) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle) return MAVSDK_LOG_STREAMING_RESULT_UNKNOWN;


    mavsdk_log_streaming_result_t result = mavsdk_log_streaming_stop_log_streaming(
        reinterpret_cast<mavsdk_log_streaming_t>(handle)    );

    return static_cast<jint>(result);
}

// ===== LogStreaming.stop_log_streamingAsyncNative =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_stopLogStreamingAsyncNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle || !callback) return;


    auto* wrapper = new StopLogStreamingCallbackWrapper(env, callback);

    mavsdk_log_streaming_stop_log_streaming_async(
        reinterpret_cast<mavsdk_log_streaming_t>(handle),        [](const mavsdk_log_streaming_result_t result, void* user_data) {
            auto* w = static_cast<StopLogStreamingCallbackWrapper*>(user_data);
            (*w)(result);
            delete w;
        },
        wrapper
    );
}


// ===== LogStreaming.subscribeLogStreamingRawNative =====
JNIEXPORT jlong JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_subscribeLogStreamingRawNative(
    JNIEnv* env,
    jobject obj,
    jobject callback) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle || !callback) return 0;


    auto* wrapper = new LogStreamingRawCallbackWrapper(env, callback);

    mavsdk_log_streaming_log_streaming_raw_handle_t subscription_handle =
        mavsdk_log_streaming_subscribe_log_streaming_raw(
            reinterpret_cast<mavsdk_log_streaming_t>(handle),            [](const mavsdk_log_streaming_log_streaming_raw_t value, void* user_data) {
                auto* w = static_cast<LogStreamingRawCallbackWrapper*>(user_data);
                (*w)(value);
            },
            wrapper
        );

    auto* handle_pair = new std::pair<
        mavsdk_log_streaming_log_streaming_raw_handle_t,
        LogStreamingRawCallbackWrapper*>(
        subscription_handle, wrapper
    );

    return reinterpret_cast<jlong>(handle_pair);
}

// ===== LogStreaming.unsubscribeLogStreamingRaw =====
JNIEXPORT void JNICALL
Java_io_mavsdk_kotlin_plugins_log_1streaming_LogStreaming_unsubscribeLogStreamingRaw(
    JNIEnv* env,
    jobject obj,
    jlong subscriptionHandle) {

    jlong handle = getHandle(env, obj, "io/mavsdk/kotlin/plugins/log_streaming/LogStreaming");
    if (!handle || !subscriptionHandle) return;

    auto* handle_pair = reinterpret_cast<
        std::pair<mavsdk_log_streaming_log_streaming_raw_handle_t,
                  LogStreamingRawCallbackWrapper*>*>(subscriptionHandle);

    if (handle_pair) {
        mavsdk_log_streaming_unsubscribe_log_streaming_raw(
            reinterpret_cast<mavsdk_log_streaming_t>(handle),
            handle_pair->first
        );
        delete handle_pair->second;
        delete handle_pair;
    }
}


} // extern "C"