name: Docker PR Image Cleanup

on:
  schedule:
    - cron: '0 3 * * 0'  # Run weekly on Sunday at 03:00
  workflow_dispatch:     # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python -m pip install requests

      - name: Run script
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: python tools/cleanup_dockerhub.py
