name: Windows Build and Test

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/docs_deploy.yml'

jobs:
  Windows-mavsdk_server:
    name: Windows mavsdk_server build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        id: cache
        with:
          path: ./build/third_party/install
          key: ${{ github.job }}-mavsdk_server-${{ hashFiles('./third_party/**') }}
      - name: disable superbuild on cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
            echo "superbuild=-DSUPERBUILD=OFF" \
              | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "cmake_prefix_path=-DCMAKE_PREFIX_PATH=$(pwd)/build/third_party/install" \
              | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: install jom
        run: |
          choco install jom
          echo "C:\Program Files\jom" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: configure
        run: cmake -GNinja \
          $env:superbuild \
          $env:cmake_prefix_path \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=install \
          -DBUILD_MAVSDK_SERVER=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DWERROR=ON \
          -Bbuild \
          -S.
      - name: build
        run: cmake --build build --config RelWithDebInfo --target install
      - name: Publish mavsdk_server binary
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'install/bin/mavsdk_server_bin.exe'
          asset_name: 'mavsdk_server_win32.exe'
          tag: ${{ github.ref }}
          overwrite: true

  Windows-mavsdk-library:
    name: Windows mavsdk library build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        id: cache
        with:
          path: ./build/third_party/install
          key: ${{ github.job }}-library-${{ hashFiles('./third_party/**') }}
      - name: disable superbuild on cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
            echo "superbuild=-DSUPERBUILD=OFF" \
              | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "cmake_prefix_path=-DCMAKE_PREFIX_PATH=$(pwd)/build/third_party/install" \
              | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: install jom
        run: |
          choco install jom
          echo "C:\Program Files\jom" \
            | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: configure
        run: cmake -GNinja \
          $env:superbuild \
          $env:cmake_prefix_path \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_INSTALL_PREFIX=install \
          -DBUILD_MAVSDK_SERVER=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -DWERROR=ON \
          -Bbuild \
          -S.
      - name: build
        run: cmake --build build --config RelWithDebInfo --target install
      - name: Create zip file from mavsdk libraries
        if: startsWith(github.ref, 'refs/tags/v')
        run: (cd install && 7z.exe a -tzip ../mavsdk-library-windows-x64.zip .)
      - name: Publish mavsdk libraries
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'mavsdk-windows-x64-release.zip'
          asset_name: 'mavsdk-library-windows-x64.zip'
          tag: ${{ github.ref }}
          overwrite: true